// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/petclinic.proto

// Protobuf Java Version: 3.25.3
package org.springframework.samples.petclinic.protobuf;

public final class Petclinic {
  private Petclinic() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoPetType_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_springframework_samples_petclinic_protobuf_ProtoPetType_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoPetTypes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_springframework_samples_petclinic_protobuf_ProtoPetTypes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoPetTypeAdd_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_springframework_samples_petclinic_protobuf_ProtoPetTypeAdd_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoPet_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_springframework_samples_petclinic_protobuf_ProtoPet_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoPets_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_springframework_samples_petclinic_protobuf_ProtoPets_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoPetAdd_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_springframework_samples_petclinic_protobuf_ProtoPetAdd_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoPetOwner_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_springframework_samples_petclinic_protobuf_ProtoPetOwner_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoPetVisit_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_springframework_samples_petclinic_protobuf_ProtoPetVisit_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoOwner_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_springframework_samples_petclinic_protobuf_ProtoOwner_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoOwners_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_springframework_samples_petclinic_protobuf_ProtoOwners_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoOwnerPet_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_springframework_samples_petclinic_protobuf_ProtoOwnerPet_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoOwnerFindByName_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_springframework_samples_petclinic_protobuf_ProtoOwnerFindByName_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoOwnerAdd_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_springframework_samples_petclinic_protobuf_ProtoOwnerAdd_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoOwnerAddPet_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_springframework_samples_petclinic_protobuf_ProtoOwnerAddPet_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoOwnerAddVisit_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_springframework_samples_petclinic_protobuf_ProtoOwnerAddVisit_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoSpecialty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_springframework_samples_petclinic_protobuf_ProtoSpecialty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoSpecialties_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_springframework_samples_petclinic_protobuf_ProtoSpecialties_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoSpecialtyAdd_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_springframework_samples_petclinic_protobuf_ProtoSpecialtyAdd_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoVet_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_springframework_samples_petclinic_protobuf_ProtoVet_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoVets_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_springframework_samples_petclinic_protobuf_ProtoVets_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoVetAdd_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_springframework_samples_petclinic_protobuf_ProtoVetAdd_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoVisit_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_springframework_samples_petclinic_protobuf_ProtoVisit_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoVisits_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_springframework_samples_petclinic_protobuf_ProtoVisits_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoVisitAdd_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_springframework_samples_petclinic_protobuf_ProtoVisitAdd_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031resources/petclinic.proto\022.org.springf" +
      "ramework.samples.petclinic.protobuf\"(\n\014P" +
      "rotoPetType\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\"_\n" +
      "\rProtoPetTypes\022N\n\010petTypes\030\001 \003(\0132<.org.s" +
      "pringframework.samples.petclinic.protobu" +
      "f.ProtoPetType\"\037\n\017ProtoPetTypeAdd\022\014\n\004nam" +
      "e\030\001 \001(\t\"\345\001\n\010ProtoPet\022\n\n\002id\030\001 \001(\005\022\014\n\004name" +
      "\030\002 \001(\t\022\022\n\nbirth_date\030\003 \001(\t\022J\n\004type\030\004 \001(\013" +
      "2<.org.springframework.samples.petclinic" +
      ".protobuf.ProtoPetType\022\020\n\010owner_id\030\005 \001(\005" +
      "\022M\n\006visits\030\006 \003(\0132=.org.springframework.s" +
      "amples.petclinic.protobuf.ProtoPetVisit\"" +
      "S\n\tProtoPets\022F\n\004pets\030\001 \003(\01328.org.springf" +
      "ramework.samples.petclinic.protobuf.Prot" +
      "oPet\"V\n\013ProtoPetAdd\022\014\n\004name\030\001 \001(\t\022\022\n\nbir" +
      "th_date\030\002 \001(\t\022\023\n\013pet_type_id\030\003 \001(\005\022\020\n\010ow" +
      "ner_id\030\004 \001(\005\"h\n\rProtoPetOwner\022\022\n\nfirst_n" +
      "ame\030\001 \001(\t\022\021\n\tlast_name\030\002 \001(\t\022\017\n\007address\030" +
      "\003 \001(\t\022\014\n\004city\030\004 \001(\t\022\021\n\ttelephone\030\005 \001(\t\"N" +
      "\n\rProtoPetVisit\022\n\n\002id\030\001 \001(\005\022\014\n\004date\030\002 \001(" +
      "\t\022\023\n\013description\030\003 \001(\t\022\016\n\006pet_id\030\004 \001(\005\"\271" +
      "\001\n\nProtoOwner\022\n\n\002id\030\001 \001(\005\022\022\n\nfirst_name\030" +
      "\002 \001(\t\022\021\n\tlast_name\030\003 \001(\t\022\017\n\007address\030\004 \001(" +
      "\t\022\014\n\004city\030\005 \001(\t\022\021\n\ttelephone\030\006 \001(\t\022F\n\004pe" +
      "ts\030\007 \003(\01328.org.springframework.samples.p" +
      "etclinic.protobuf.ProtoPet\"Y\n\013ProtoOwner" +
      "s\022J\n\006owners\030\001 \003(\0132:.org.springframework." +
      "samples.petclinic.protobuf.ProtoOwner\"O\n" +
      "\rProtoOwnerPet\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t" +
      "\022\022\n\nbirth_date\030\003 \001(\t\022\020\n\010pet_type\030\004 \001(\t\")" +
      "\n\024ProtoOwnerFindByName\022\021\n\tlast_name\030\001 \001(" +
      "\t\"h\n\rProtoOwnerAdd\022\022\n\nfirst_name\030\002 \001(\t\022\021" +
      "\n\tlast_name\030\003 \001(\t\022\017\n\007address\030\004 \001(\t\022\014\n\004ci" +
      "ty\030\005 \001(\t\022\021\n\ttelephone\030\006 \001(\t\"\200\001\n\020ProtoOwn" +
      "erAddPet\022\014\n\004name\030\001 \001(\t\022\022\n\nbirth_date\030\002 \001" +
      "(\t\022J\n\004type\030\003 \001(\0132<.org.springframework.s" +
      "amples.petclinic.protobuf.ProtoPetType\"C" +
      "\n\022ProtoOwnerAddVisit\022\022\n\nvisit_date\030\003 \001(\t" +
      "\022\031\n\021visit_description\030\004 \001(\t\"*\n\016ProtoSpec" +
      "ialty\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\"g\n\020Proto" +
      "Specialties\022S\n\013specialties\030\001 \003(\0132>.org.s" +
      "pringframework.samples.petclinic.protobu" +
      "f.ProtoSpecialty\"!\n\021ProtoSpecialtyAdd\022\014\n" +
      "\004name\030\001 \001(\t\"\222\001\n\010ProtoVet\022\n\n\002id\030\001 \001(\005\022\022\n\n" +
      "first_name\030\002 \001(\t\022\021\n\tlast_name\030\003 \001(\t\022S\n\013s" +
      "pecialties\030\004 \003(\0132>.org.springframework.s" +
      "amples.petclinic.protobuf.ProtoSpecialty" +
      "\"S\n\tProtoVets\022F\n\004vets\030\001 \003(\01328.org.spring" +
      "framework.samples.petclinic.protobuf.Pro" +
      "toVet\"\211\001\n\013ProtoVetAdd\022\022\n\nfirst_name\030\001 \001(" +
      "\t\022\021\n\tlast_name\030\002 \001(\t\022S\n\013specialties\030\003 \003(" +
      "\0132>.org.springframework.samples.petclini" +
      "c.protobuf.ProtoSpecialty\"K\n\nProtoVisit\022" +
      "\n\n\002id\030\001 \001(\005\022\014\n\004date\030\002 \001(\t\022\023\n\013description" +
      "\030\003 \001(\t\022\016\n\006pet_id\030\004 \001(\005\"Y\n\013ProtoVisits\022J\n" +
      "\006visits\030\001 \003(\0132:.org.springframework.samp" +
      "les.petclinic.protobuf.ProtoVisit\"2\n\rPro" +
      "toVisitAdd\022\014\n\004date\030\001 \001(\t\022\023\n\013description\030" +
      "\002 \001(\tB2\n.org.springframework.samples.pet" +
      "clinic.protobufP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoPetType_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoPetType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_springframework_samples_petclinic_protobuf_ProtoPetType_descriptor,
        new java.lang.String[] { "Id", "Name", });
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoPetTypes_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoPetTypes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_springframework_samples_petclinic_protobuf_ProtoPetTypes_descriptor,
        new java.lang.String[] { "PetTypes", });
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoPetTypeAdd_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoPetTypeAdd_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_springframework_samples_petclinic_protobuf_ProtoPetTypeAdd_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoPet_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoPet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_springframework_samples_petclinic_protobuf_ProtoPet_descriptor,
        new java.lang.String[] { "Id", "Name", "BirthDate", "Type", "OwnerId", "Visits", });
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoPets_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoPets_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_springframework_samples_petclinic_protobuf_ProtoPets_descriptor,
        new java.lang.String[] { "Pets", });
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoPetAdd_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoPetAdd_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_springframework_samples_petclinic_protobuf_ProtoPetAdd_descriptor,
        new java.lang.String[] { "Name", "BirthDate", "PetTypeId", "OwnerId", });
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoPetOwner_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoPetOwner_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_springframework_samples_petclinic_protobuf_ProtoPetOwner_descriptor,
        new java.lang.String[] { "FirstName", "LastName", "Address", "City", "Telephone", });
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoPetVisit_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoPetVisit_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_springframework_samples_petclinic_protobuf_ProtoPetVisit_descriptor,
        new java.lang.String[] { "Id", "Date", "Description", "PetId", });
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoOwner_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoOwner_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_springframework_samples_petclinic_protobuf_ProtoOwner_descriptor,
        new java.lang.String[] { "Id", "FirstName", "LastName", "Address", "City", "Telephone", "Pets", });
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoOwners_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoOwners_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_springframework_samples_petclinic_protobuf_ProtoOwners_descriptor,
        new java.lang.String[] { "Owners", });
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoOwnerPet_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoOwnerPet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_springframework_samples_petclinic_protobuf_ProtoOwnerPet_descriptor,
        new java.lang.String[] { "Id", "Name", "BirthDate", "PetType", });
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoOwnerFindByName_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoOwnerFindByName_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_springframework_samples_petclinic_protobuf_ProtoOwnerFindByName_descriptor,
        new java.lang.String[] { "LastName", });
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoOwnerAdd_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoOwnerAdd_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_springframework_samples_petclinic_protobuf_ProtoOwnerAdd_descriptor,
        new java.lang.String[] { "FirstName", "LastName", "Address", "City", "Telephone", });
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoOwnerAddPet_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoOwnerAddPet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_springframework_samples_petclinic_protobuf_ProtoOwnerAddPet_descriptor,
        new java.lang.String[] { "Name", "BirthDate", "Type", });
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoOwnerAddVisit_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoOwnerAddVisit_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_springframework_samples_petclinic_protobuf_ProtoOwnerAddVisit_descriptor,
        new java.lang.String[] { "VisitDate", "VisitDescription", });
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoSpecialty_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoSpecialty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_springframework_samples_petclinic_protobuf_ProtoSpecialty_descriptor,
        new java.lang.String[] { "Id", "Name", });
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoSpecialties_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoSpecialties_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_springframework_samples_petclinic_protobuf_ProtoSpecialties_descriptor,
        new java.lang.String[] { "Specialties", });
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoSpecialtyAdd_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoSpecialtyAdd_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_springframework_samples_petclinic_protobuf_ProtoSpecialtyAdd_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoVet_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoVet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_springframework_samples_petclinic_protobuf_ProtoVet_descriptor,
        new java.lang.String[] { "Id", "FirstName", "LastName", "Specialties", });
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoVets_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoVets_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_springframework_samples_petclinic_protobuf_ProtoVets_descriptor,
        new java.lang.String[] { "Vets", });
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoVetAdd_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoVetAdd_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_springframework_samples_petclinic_protobuf_ProtoVetAdd_descriptor,
        new java.lang.String[] { "FirstName", "LastName", "Specialties", });
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoVisit_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoVisit_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_springframework_samples_petclinic_protobuf_ProtoVisit_descriptor,
        new java.lang.String[] { "Id", "Date", "Description", "PetId", });
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoVisits_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoVisits_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_springframework_samples_petclinic_protobuf_ProtoVisits_descriptor,
        new java.lang.String[] { "Visits", });
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoVisitAdd_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_org_springframework_samples_petclinic_protobuf_ProtoVisitAdd_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_springframework_samples_petclinic_protobuf_ProtoVisitAdd_descriptor,
        new java.lang.String[] { "Date", "Description", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
