// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/petclinic.proto

// Protobuf Java Version: 3.25.3
package org.springframework.samples.petclinic.protobuf;

public interface ProtoOwnersOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.springframework.samples.petclinic.protobuf.ProtoOwners)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoOwner owners = 1;</code>
   */
  java.util.List<org.springframework.samples.petclinic.protobuf.ProtoOwner> 
      getOwnersList();
  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoOwner owners = 1;</code>
   */
  org.springframework.samples.petclinic.protobuf.ProtoOwner getOwners(int index);
  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoOwner owners = 1;</code>
   */
  int getOwnersCount();
  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoOwner owners = 1;</code>
   */
  java.util.List<? extends org.springframework.samples.petclinic.protobuf.ProtoOwnerOrBuilder> 
      getOwnersOrBuilderList();
  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoOwner owners = 1;</code>
   */
  org.springframework.samples.petclinic.protobuf.ProtoOwnerOrBuilder getOwnersOrBuilder(
      int index);
}
