// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/petclinic.proto

// Protobuf Java Version: 3.25.3
package org.springframework.samples.petclinic.protobuf;

public interface ProtoPetOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.springframework.samples.petclinic.protobuf.ProtoPet)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string birth_date = 3;</code>
   * @return The birthDate.
   */
  java.lang.String getBirthDate();
  /**
   * <code>string birth_date = 3;</code>
   * @return The bytes for birthDate.
   */
  com.google.protobuf.ByteString
      getBirthDateBytes();

  /**
   * <code>.org.springframework.samples.petclinic.protobuf.ProtoPetType type = 4;</code>
   * @return Whether the type field is set.
   */
  boolean hasType();
  /**
   * <code>.org.springframework.samples.petclinic.protobuf.ProtoPetType type = 4;</code>
   * @return The type.
   */
  org.springframework.samples.petclinic.protobuf.ProtoPetType getType();
  /**
   * <code>.org.springframework.samples.petclinic.protobuf.ProtoPetType type = 4;</code>
   */
  org.springframework.samples.petclinic.protobuf.ProtoPetTypeOrBuilder getTypeOrBuilder();

  /**
   * <code>int32 owner_id = 5;</code>
   * @return The ownerId.
   */
  int getOwnerId();

  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPetVisit visits = 6;</code>
   */
  java.util.List<org.springframework.samples.petclinic.protobuf.ProtoPetVisit> 
      getVisitsList();
  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPetVisit visits = 6;</code>
   */
  org.springframework.samples.petclinic.protobuf.ProtoPetVisit getVisits(int index);
  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPetVisit visits = 6;</code>
   */
  int getVisitsCount();
  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPetVisit visits = 6;</code>
   */
  java.util.List<? extends org.springframework.samples.petclinic.protobuf.ProtoPetVisitOrBuilder> 
      getVisitsOrBuilderList();
  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPetVisit visits = 6;</code>
   */
  org.springframework.samples.petclinic.protobuf.ProtoPetVisitOrBuilder getVisitsOrBuilder(
      int index);
}
