// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/petclinic.proto

// Protobuf Java Version: 3.25.3
package org.springframework.samples.petclinic.protobuf;

public interface ProtoVisitOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.springframework.samples.petclinic.protobuf.ProtoVisit)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string date = 2;</code>
   * @return The date.
   */
  java.lang.String getDate();
  /**
   * <code>string date = 2;</code>
   * @return The bytes for date.
   */
  com.google.protobuf.ByteString
      getDateBytes();

  /**
   * <code>string description = 3;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 3;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>string pet_name = 4;</code>
   * @return The petName.
   */
  java.lang.String getPetName();
  /**
   * <code>string pet_name = 4;</code>
   * @return The bytes for petName.
   */
  com.google.protobuf.ByteString
      getPetNameBytes();
}
