// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/petclinic.proto

// Protobuf Java Version: 3.25.3
package org.springframework.samples.petclinic.protobuf;

public interface ProtoOwnerPetOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.springframework.samples.petclinic.protobuf.ProtoOwnerPet)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string birth_date = 3;</code>
   * @return The birthDate.
   */
  java.lang.String getBirthDate();
  /**
   * <code>string birth_date = 3;</code>
   * @return The bytes for birthDate.
   */
  com.google.protobuf.ByteString
      getBirthDateBytes();

  /**
   * <code>string pet_type = 4;</code>
   * @return The petType.
   */
  java.lang.String getPetType();
  /**
   * <code>string pet_type = 4;</code>
   * @return The bytes for petType.
   */
  com.google.protobuf.ByteString
      getPetTypeBytes();
}
