// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/petclinic.proto

// Protobuf Java Version: 3.25.3
package org.springframework.samples.petclinic.protobuf;

public interface ProtoVetOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.springframework.samples.petclinic.protobuf.ProtoVet)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string first_name = 2;</code>
   * @return The firstName.
   */
  java.lang.String getFirstName();
  /**
   * <code>string first_name = 2;</code>
   * @return The bytes for firstName.
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string last_name = 3;</code>
   * @return The lastName.
   */
  java.lang.String getLastName();
  /**
   * <code>string last_name = 3;</code>
   * @return The bytes for lastName.
   */
  com.google.protobuf.ByteString
      getLastNameBytes();

  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoSpecialty specialties = 4;</code>
   */
  java.util.List<org.springframework.samples.petclinic.protobuf.ProtoSpecialty> 
      getSpecialtiesList();
  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoSpecialty specialties = 4;</code>
   */
  org.springframework.samples.petclinic.protobuf.ProtoSpecialty getSpecialties(int index);
  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoSpecialty specialties = 4;</code>
   */
  int getSpecialtiesCount();
  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoSpecialty specialties = 4;</code>
   */
  java.util.List<? extends org.springframework.samples.petclinic.protobuf.ProtoSpecialtyOrBuilder> 
      getSpecialtiesOrBuilderList();
  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoSpecialty specialties = 4;</code>
   */
  org.springframework.samples.petclinic.protobuf.ProtoSpecialtyOrBuilder getSpecialtiesOrBuilder(
      int index);
}
