// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/petclinic.proto

// Protobuf Java Version: 3.25.3
package org.springframework.samples.petclinic.protobuf;

public interface ProtoSpecialtiesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.springframework.samples.petclinic.protobuf.ProtoSpecialties)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoSpecialty specialties = 1;</code>
   */
  java.util.List<org.springframework.samples.petclinic.protobuf.ProtoSpecialty> 
      getSpecialtiesList();
  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoSpecialty specialties = 1;</code>
   */
  org.springframework.samples.petclinic.protobuf.ProtoSpecialty getSpecialties(int index);
  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoSpecialty specialties = 1;</code>
   */
  int getSpecialtiesCount();
  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoSpecialty specialties = 1;</code>
   */
  java.util.List<? extends org.springframework.samples.petclinic.protobuf.ProtoSpecialtyOrBuilder> 
      getSpecialtiesOrBuilderList();
  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoSpecialty specialties = 1;</code>
   */
  org.springframework.samples.petclinic.protobuf.ProtoSpecialtyOrBuilder getSpecialtiesOrBuilder(
      int index);
}
