// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/petclinic.proto

// Protobuf Java Version: 3.25.3
package org.springframework.samples.petclinic.protobuf;

public interface ProtoOwnerAddVisitOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.springframework.samples.petclinic.protobuf.ProtoOwnerAddVisit)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string visit_date = 3;</code>
   * @return The visitDate.
   */
  java.lang.String getVisitDate();
  /**
   * <code>string visit_date = 3;</code>
   * @return The bytes for visitDate.
   */
  com.google.protobuf.ByteString
      getVisitDateBytes();

  /**
   * <code>string visit_description = 4;</code>
   * @return The visitDescription.
   */
  java.lang.String getVisitDescription();
  /**
   * <code>string visit_description = 4;</code>
   * @return The bytes for visitDescription.
   */
  com.google.protobuf.ByteString
      getVisitDescriptionBytes();
}
