// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/petclinic.proto

// Protobuf Java Version: 3.25.3
package org.springframework.samples.petclinic.protobuf;

public interface ProtoPetTypesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.springframework.samples.petclinic.protobuf.ProtoPetTypes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPetType petTypes = 1;</code>
   */
  java.util.List<org.springframework.samples.petclinic.protobuf.ProtoPetType> 
      getPetTypesList();
  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPetType petTypes = 1;</code>
   */
  org.springframework.samples.petclinic.protobuf.ProtoPetType getPetTypes(int index);
  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPetType petTypes = 1;</code>
   */
  int getPetTypesCount();
  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPetType petTypes = 1;</code>
   */
  java.util.List<? extends org.springframework.samples.petclinic.protobuf.ProtoPetTypeOrBuilder> 
      getPetTypesOrBuilderList();
  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPetType petTypes = 1;</code>
   */
  org.springframework.samples.petclinic.protobuf.ProtoPetTypeOrBuilder getPetTypesOrBuilder(
      int index);
}
