// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/petclinic.proto

// Protobuf Java Version: 3.25.3
package org.springframework.samples.petclinic.protobuf;

/**
 * Protobuf type {@code org.springframework.samples.petclinic.protobuf.ProtoVisits}
 */
public final class ProtoVisits extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.springframework.samples.petclinic.protobuf.ProtoVisits)
    ProtoVisitsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ProtoVisits.newBuilder() to construct.
  private ProtoVisits(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProtoVisits() {
    visits_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ProtoVisits();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.springframework.samples.petclinic.protobuf.Petclinic.internal_static_org_springframework_samples_petclinic_protobuf_ProtoVisits_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.springframework.samples.petclinic.protobuf.Petclinic.internal_static_org_springframework_samples_petclinic_protobuf_ProtoVisits_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.springframework.samples.petclinic.protobuf.ProtoVisits.class, org.springframework.samples.petclinic.protobuf.ProtoVisits.Builder.class);
  }

  public static final int VISITS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<org.springframework.samples.petclinic.protobuf.ProtoVisit> visits_;
  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoVisit visits = 1;</code>
   */
  @java.lang.Override
  public java.util.List<org.springframework.samples.petclinic.protobuf.ProtoVisit> getVisitsList() {
    return visits_;
  }
  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoVisit visits = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.springframework.samples.petclinic.protobuf.ProtoVisitOrBuilder> 
      getVisitsOrBuilderList() {
    return visits_;
  }
  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoVisit visits = 1;</code>
   */
  @java.lang.Override
  public int getVisitsCount() {
    return visits_.size();
  }
  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoVisit visits = 1;</code>
   */
  @java.lang.Override
  public org.springframework.samples.petclinic.protobuf.ProtoVisit getVisits(int index) {
    return visits_.get(index);
  }
  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoVisit visits = 1;</code>
   */
  @java.lang.Override
  public org.springframework.samples.petclinic.protobuf.ProtoVisitOrBuilder getVisitsOrBuilder(
      int index) {
    return visits_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < visits_.size(); i++) {
      output.writeMessage(1, visits_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < visits_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, visits_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.springframework.samples.petclinic.protobuf.ProtoVisits)) {
      return super.equals(obj);
    }
    org.springframework.samples.petclinic.protobuf.ProtoVisits other = (org.springframework.samples.petclinic.protobuf.ProtoVisits) obj;

    if (!getVisitsList()
        .equals(other.getVisitsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getVisitsCount() > 0) {
      hash = (37 * hash) + VISITS_FIELD_NUMBER;
      hash = (53 * hash) + getVisitsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.springframework.samples.petclinic.protobuf.ProtoVisits parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.springframework.samples.petclinic.protobuf.ProtoVisits parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.springframework.samples.petclinic.protobuf.ProtoVisits parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.springframework.samples.petclinic.protobuf.ProtoVisits parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.springframework.samples.petclinic.protobuf.ProtoVisits parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.springframework.samples.petclinic.protobuf.ProtoVisits parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.springframework.samples.petclinic.protobuf.ProtoVisits parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.springframework.samples.petclinic.protobuf.ProtoVisits parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.springframework.samples.petclinic.protobuf.ProtoVisits parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.springframework.samples.petclinic.protobuf.ProtoVisits parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.springframework.samples.petclinic.protobuf.ProtoVisits parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.springframework.samples.petclinic.protobuf.ProtoVisits parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.springframework.samples.petclinic.protobuf.ProtoVisits prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.springframework.samples.petclinic.protobuf.ProtoVisits}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.springframework.samples.petclinic.protobuf.ProtoVisits)
      org.springframework.samples.petclinic.protobuf.ProtoVisitsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.springframework.samples.petclinic.protobuf.Petclinic.internal_static_org_springframework_samples_petclinic_protobuf_ProtoVisits_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.springframework.samples.petclinic.protobuf.Petclinic.internal_static_org_springframework_samples_petclinic_protobuf_ProtoVisits_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.springframework.samples.petclinic.protobuf.ProtoVisits.class, org.springframework.samples.petclinic.protobuf.ProtoVisits.Builder.class);
    }

    // Construct using org.springframework.samples.petclinic.protobuf.ProtoVisits.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (visitsBuilder_ == null) {
        visits_ = java.util.Collections.emptyList();
      } else {
        visits_ = null;
        visitsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.springframework.samples.petclinic.protobuf.Petclinic.internal_static_org_springframework_samples_petclinic_protobuf_ProtoVisits_descriptor;
    }

    @java.lang.Override
    public org.springframework.samples.petclinic.protobuf.ProtoVisits getDefaultInstanceForType() {
      return org.springframework.samples.petclinic.protobuf.ProtoVisits.getDefaultInstance();
    }

    @java.lang.Override
    public org.springframework.samples.petclinic.protobuf.ProtoVisits build() {
      org.springframework.samples.petclinic.protobuf.ProtoVisits result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.springframework.samples.petclinic.protobuf.ProtoVisits buildPartial() {
      org.springframework.samples.petclinic.protobuf.ProtoVisits result = new org.springframework.samples.petclinic.protobuf.ProtoVisits(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(org.springframework.samples.petclinic.protobuf.ProtoVisits result) {
      if (visitsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          visits_ = java.util.Collections.unmodifiableList(visits_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.visits_ = visits_;
      } else {
        result.visits_ = visitsBuilder_.build();
      }
    }

    private void buildPartial0(org.springframework.samples.petclinic.protobuf.ProtoVisits result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.springframework.samples.petclinic.protobuf.ProtoVisits) {
        return mergeFrom((org.springframework.samples.petclinic.protobuf.ProtoVisits)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.springframework.samples.petclinic.protobuf.ProtoVisits other) {
      if (other == org.springframework.samples.petclinic.protobuf.ProtoVisits.getDefaultInstance()) return this;
      if (visitsBuilder_ == null) {
        if (!other.visits_.isEmpty()) {
          if (visits_.isEmpty()) {
            visits_ = other.visits_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureVisitsIsMutable();
            visits_.addAll(other.visits_);
          }
          onChanged();
        }
      } else {
        if (!other.visits_.isEmpty()) {
          if (visitsBuilder_.isEmpty()) {
            visitsBuilder_.dispose();
            visitsBuilder_ = null;
            visits_ = other.visits_;
            bitField0_ = (bitField0_ & ~0x00000001);
            visitsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getVisitsFieldBuilder() : null;
          } else {
            visitsBuilder_.addAllMessages(other.visits_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              org.springframework.samples.petclinic.protobuf.ProtoVisit m =
                  input.readMessage(
                      org.springframework.samples.petclinic.protobuf.ProtoVisit.parser(),
                      extensionRegistry);
              if (visitsBuilder_ == null) {
                ensureVisitsIsMutable();
                visits_.add(m);
              } else {
                visitsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<org.springframework.samples.petclinic.protobuf.ProtoVisit> visits_ =
      java.util.Collections.emptyList();
    private void ensureVisitsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        visits_ = new java.util.ArrayList<org.springframework.samples.petclinic.protobuf.ProtoVisit>(visits_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.springframework.samples.petclinic.protobuf.ProtoVisit, org.springframework.samples.petclinic.protobuf.ProtoVisit.Builder, org.springframework.samples.petclinic.protobuf.ProtoVisitOrBuilder> visitsBuilder_;

    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoVisit visits = 1;</code>
     */
    public java.util.List<org.springframework.samples.petclinic.protobuf.ProtoVisit> getVisitsList() {
      if (visitsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(visits_);
      } else {
        return visitsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoVisit visits = 1;</code>
     */
    public int getVisitsCount() {
      if (visitsBuilder_ == null) {
        return visits_.size();
      } else {
        return visitsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoVisit visits = 1;</code>
     */
    public org.springframework.samples.petclinic.protobuf.ProtoVisit getVisits(int index) {
      if (visitsBuilder_ == null) {
        return visits_.get(index);
      } else {
        return visitsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoVisit visits = 1;</code>
     */
    public Builder setVisits(
        int index, org.springframework.samples.petclinic.protobuf.ProtoVisit value) {
      if (visitsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVisitsIsMutable();
        visits_.set(index, value);
        onChanged();
      } else {
        visitsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoVisit visits = 1;</code>
     */
    public Builder setVisits(
        int index, org.springframework.samples.petclinic.protobuf.ProtoVisit.Builder builderForValue) {
      if (visitsBuilder_ == null) {
        ensureVisitsIsMutable();
        visits_.set(index, builderForValue.build());
        onChanged();
      } else {
        visitsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoVisit visits = 1;</code>
     */
    public Builder addVisits(org.springframework.samples.petclinic.protobuf.ProtoVisit value) {
      if (visitsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVisitsIsMutable();
        visits_.add(value);
        onChanged();
      } else {
        visitsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoVisit visits = 1;</code>
     */
    public Builder addVisits(
        int index, org.springframework.samples.petclinic.protobuf.ProtoVisit value) {
      if (visitsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVisitsIsMutable();
        visits_.add(index, value);
        onChanged();
      } else {
        visitsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoVisit visits = 1;</code>
     */
    public Builder addVisits(
        org.springframework.samples.petclinic.protobuf.ProtoVisit.Builder builderForValue) {
      if (visitsBuilder_ == null) {
        ensureVisitsIsMutable();
        visits_.add(builderForValue.build());
        onChanged();
      } else {
        visitsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoVisit visits = 1;</code>
     */
    public Builder addVisits(
        int index, org.springframework.samples.petclinic.protobuf.ProtoVisit.Builder builderForValue) {
      if (visitsBuilder_ == null) {
        ensureVisitsIsMutable();
        visits_.add(index, builderForValue.build());
        onChanged();
      } else {
        visitsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoVisit visits = 1;</code>
     */
    public Builder addAllVisits(
        java.lang.Iterable<? extends org.springframework.samples.petclinic.protobuf.ProtoVisit> values) {
      if (visitsBuilder_ == null) {
        ensureVisitsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, visits_);
        onChanged();
      } else {
        visitsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoVisit visits = 1;</code>
     */
    public Builder clearVisits() {
      if (visitsBuilder_ == null) {
        visits_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        visitsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoVisit visits = 1;</code>
     */
    public Builder removeVisits(int index) {
      if (visitsBuilder_ == null) {
        ensureVisitsIsMutable();
        visits_.remove(index);
        onChanged();
      } else {
        visitsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoVisit visits = 1;</code>
     */
    public org.springframework.samples.petclinic.protobuf.ProtoVisit.Builder getVisitsBuilder(
        int index) {
      return getVisitsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoVisit visits = 1;</code>
     */
    public org.springframework.samples.petclinic.protobuf.ProtoVisitOrBuilder getVisitsOrBuilder(
        int index) {
      if (visitsBuilder_ == null) {
        return visits_.get(index);  } else {
        return visitsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoVisit visits = 1;</code>
     */
    public java.util.List<? extends org.springframework.samples.petclinic.protobuf.ProtoVisitOrBuilder> 
         getVisitsOrBuilderList() {
      if (visitsBuilder_ != null) {
        return visitsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(visits_);
      }
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoVisit visits = 1;</code>
     */
    public org.springframework.samples.petclinic.protobuf.ProtoVisit.Builder addVisitsBuilder() {
      return getVisitsFieldBuilder().addBuilder(
          org.springframework.samples.petclinic.protobuf.ProtoVisit.getDefaultInstance());
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoVisit visits = 1;</code>
     */
    public org.springframework.samples.petclinic.protobuf.ProtoVisit.Builder addVisitsBuilder(
        int index) {
      return getVisitsFieldBuilder().addBuilder(
          index, org.springframework.samples.petclinic.protobuf.ProtoVisit.getDefaultInstance());
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoVisit visits = 1;</code>
     */
    public java.util.List<org.springframework.samples.petclinic.protobuf.ProtoVisit.Builder> 
         getVisitsBuilderList() {
      return getVisitsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.springframework.samples.petclinic.protobuf.ProtoVisit, org.springframework.samples.petclinic.protobuf.ProtoVisit.Builder, org.springframework.samples.petclinic.protobuf.ProtoVisitOrBuilder> 
        getVisitsFieldBuilder() {
      if (visitsBuilder_ == null) {
        visitsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.springframework.samples.petclinic.protobuf.ProtoVisit, org.springframework.samples.petclinic.protobuf.ProtoVisit.Builder, org.springframework.samples.petclinic.protobuf.ProtoVisitOrBuilder>(
                visits_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        visits_ = null;
      }
      return visitsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.springframework.samples.petclinic.protobuf.ProtoVisits)
  }

  // @@protoc_insertion_point(class_scope:org.springframework.samples.petclinic.protobuf.ProtoVisits)
  private static final org.springframework.samples.petclinic.protobuf.ProtoVisits DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.springframework.samples.petclinic.protobuf.ProtoVisits();
  }

  public static org.springframework.samples.petclinic.protobuf.ProtoVisits getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProtoVisits>
      PARSER = new com.google.protobuf.AbstractParser<ProtoVisits>() {
    @java.lang.Override
    public ProtoVisits parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ProtoVisits> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProtoVisits> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.springframework.samples.petclinic.protobuf.ProtoVisits getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

