// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/petclinic.proto

// Protobuf Java Version: 3.25.3
package org.springframework.samples.petclinic.protobuf;

/**
 * Protobuf type {@code org.springframework.samples.petclinic.protobuf.ProtoSpecialties}
 */
public final class ProtoSpecialties extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.springframework.samples.petclinic.protobuf.ProtoSpecialties)
    ProtoSpecialtiesOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ProtoSpecialties.newBuilder() to construct.
  private ProtoSpecialties(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProtoSpecialties() {
    specialties_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ProtoSpecialties();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.springframework.samples.petclinic.protobuf.Petclinic.internal_static_org_springframework_samples_petclinic_protobuf_ProtoSpecialties_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.springframework.samples.petclinic.protobuf.Petclinic.internal_static_org_springframework_samples_petclinic_protobuf_ProtoSpecialties_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.springframework.samples.petclinic.protobuf.ProtoSpecialties.class, org.springframework.samples.petclinic.protobuf.ProtoSpecialties.Builder.class);
  }

  public static final int SPECIALTIES_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<org.springframework.samples.petclinic.protobuf.ProtoSpecialty> specialties_;
  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoSpecialty specialties = 1;</code>
   */
  @java.lang.Override
  public java.util.List<org.springframework.samples.petclinic.protobuf.ProtoSpecialty> getSpecialtiesList() {
    return specialties_;
  }
  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoSpecialty specialties = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.springframework.samples.petclinic.protobuf.ProtoSpecialtyOrBuilder> 
      getSpecialtiesOrBuilderList() {
    return specialties_;
  }
  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoSpecialty specialties = 1;</code>
   */
  @java.lang.Override
  public int getSpecialtiesCount() {
    return specialties_.size();
  }
  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoSpecialty specialties = 1;</code>
   */
  @java.lang.Override
  public org.springframework.samples.petclinic.protobuf.ProtoSpecialty getSpecialties(int index) {
    return specialties_.get(index);
  }
  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoSpecialty specialties = 1;</code>
   */
  @java.lang.Override
  public org.springframework.samples.petclinic.protobuf.ProtoSpecialtyOrBuilder getSpecialtiesOrBuilder(
      int index) {
    return specialties_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < specialties_.size(); i++) {
      output.writeMessage(1, specialties_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < specialties_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, specialties_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.springframework.samples.petclinic.protobuf.ProtoSpecialties)) {
      return super.equals(obj);
    }
    org.springframework.samples.petclinic.protobuf.ProtoSpecialties other = (org.springframework.samples.petclinic.protobuf.ProtoSpecialties) obj;

    if (!getSpecialtiesList()
        .equals(other.getSpecialtiesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getSpecialtiesCount() > 0) {
      hash = (37 * hash) + SPECIALTIES_FIELD_NUMBER;
      hash = (53 * hash) + getSpecialtiesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.springframework.samples.petclinic.protobuf.ProtoSpecialties parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.springframework.samples.petclinic.protobuf.ProtoSpecialties parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.springframework.samples.petclinic.protobuf.ProtoSpecialties parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.springframework.samples.petclinic.protobuf.ProtoSpecialties parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.springframework.samples.petclinic.protobuf.ProtoSpecialties parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.springframework.samples.petclinic.protobuf.ProtoSpecialties parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.springframework.samples.petclinic.protobuf.ProtoSpecialties parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.springframework.samples.petclinic.protobuf.ProtoSpecialties parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.springframework.samples.petclinic.protobuf.ProtoSpecialties parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.springframework.samples.petclinic.protobuf.ProtoSpecialties parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.springframework.samples.petclinic.protobuf.ProtoSpecialties parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.springframework.samples.petclinic.protobuf.ProtoSpecialties parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.springframework.samples.petclinic.protobuf.ProtoSpecialties prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.springframework.samples.petclinic.protobuf.ProtoSpecialties}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.springframework.samples.petclinic.protobuf.ProtoSpecialties)
      org.springframework.samples.petclinic.protobuf.ProtoSpecialtiesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.springframework.samples.petclinic.protobuf.Petclinic.internal_static_org_springframework_samples_petclinic_protobuf_ProtoSpecialties_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.springframework.samples.petclinic.protobuf.Petclinic.internal_static_org_springframework_samples_petclinic_protobuf_ProtoSpecialties_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.springframework.samples.petclinic.protobuf.ProtoSpecialties.class, org.springframework.samples.petclinic.protobuf.ProtoSpecialties.Builder.class);
    }

    // Construct using org.springframework.samples.petclinic.protobuf.ProtoSpecialties.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (specialtiesBuilder_ == null) {
        specialties_ = java.util.Collections.emptyList();
      } else {
        specialties_ = null;
        specialtiesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.springframework.samples.petclinic.protobuf.Petclinic.internal_static_org_springframework_samples_petclinic_protobuf_ProtoSpecialties_descriptor;
    }

    @java.lang.Override
    public org.springframework.samples.petclinic.protobuf.ProtoSpecialties getDefaultInstanceForType() {
      return org.springframework.samples.petclinic.protobuf.ProtoSpecialties.getDefaultInstance();
    }

    @java.lang.Override
    public org.springframework.samples.petclinic.protobuf.ProtoSpecialties build() {
      org.springframework.samples.petclinic.protobuf.ProtoSpecialties result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.springframework.samples.petclinic.protobuf.ProtoSpecialties buildPartial() {
      org.springframework.samples.petclinic.protobuf.ProtoSpecialties result = new org.springframework.samples.petclinic.protobuf.ProtoSpecialties(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(org.springframework.samples.petclinic.protobuf.ProtoSpecialties result) {
      if (specialtiesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          specialties_ = java.util.Collections.unmodifiableList(specialties_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.specialties_ = specialties_;
      } else {
        result.specialties_ = specialtiesBuilder_.build();
      }
    }

    private void buildPartial0(org.springframework.samples.petclinic.protobuf.ProtoSpecialties result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.springframework.samples.petclinic.protobuf.ProtoSpecialties) {
        return mergeFrom((org.springframework.samples.petclinic.protobuf.ProtoSpecialties)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.springframework.samples.petclinic.protobuf.ProtoSpecialties other) {
      if (other == org.springframework.samples.petclinic.protobuf.ProtoSpecialties.getDefaultInstance()) return this;
      if (specialtiesBuilder_ == null) {
        if (!other.specialties_.isEmpty()) {
          if (specialties_.isEmpty()) {
            specialties_ = other.specialties_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSpecialtiesIsMutable();
            specialties_.addAll(other.specialties_);
          }
          onChanged();
        }
      } else {
        if (!other.specialties_.isEmpty()) {
          if (specialtiesBuilder_.isEmpty()) {
            specialtiesBuilder_.dispose();
            specialtiesBuilder_ = null;
            specialties_ = other.specialties_;
            bitField0_ = (bitField0_ & ~0x00000001);
            specialtiesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSpecialtiesFieldBuilder() : null;
          } else {
            specialtiesBuilder_.addAllMessages(other.specialties_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              org.springframework.samples.petclinic.protobuf.ProtoSpecialty m =
                  input.readMessage(
                      org.springframework.samples.petclinic.protobuf.ProtoSpecialty.parser(),
                      extensionRegistry);
              if (specialtiesBuilder_ == null) {
                ensureSpecialtiesIsMutable();
                specialties_.add(m);
              } else {
                specialtiesBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<org.springframework.samples.petclinic.protobuf.ProtoSpecialty> specialties_ =
      java.util.Collections.emptyList();
    private void ensureSpecialtiesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        specialties_ = new java.util.ArrayList<org.springframework.samples.petclinic.protobuf.ProtoSpecialty>(specialties_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.springframework.samples.petclinic.protobuf.ProtoSpecialty, org.springframework.samples.petclinic.protobuf.ProtoSpecialty.Builder, org.springframework.samples.petclinic.protobuf.ProtoSpecialtyOrBuilder> specialtiesBuilder_;

    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoSpecialty specialties = 1;</code>
     */
    public java.util.List<org.springframework.samples.petclinic.protobuf.ProtoSpecialty> getSpecialtiesList() {
      if (specialtiesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(specialties_);
      } else {
        return specialtiesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoSpecialty specialties = 1;</code>
     */
    public int getSpecialtiesCount() {
      if (specialtiesBuilder_ == null) {
        return specialties_.size();
      } else {
        return specialtiesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoSpecialty specialties = 1;</code>
     */
    public org.springframework.samples.petclinic.protobuf.ProtoSpecialty getSpecialties(int index) {
      if (specialtiesBuilder_ == null) {
        return specialties_.get(index);
      } else {
        return specialtiesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoSpecialty specialties = 1;</code>
     */
    public Builder setSpecialties(
        int index, org.springframework.samples.petclinic.protobuf.ProtoSpecialty value) {
      if (specialtiesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSpecialtiesIsMutable();
        specialties_.set(index, value);
        onChanged();
      } else {
        specialtiesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoSpecialty specialties = 1;</code>
     */
    public Builder setSpecialties(
        int index, org.springframework.samples.petclinic.protobuf.ProtoSpecialty.Builder builderForValue) {
      if (specialtiesBuilder_ == null) {
        ensureSpecialtiesIsMutable();
        specialties_.set(index, builderForValue.build());
        onChanged();
      } else {
        specialtiesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoSpecialty specialties = 1;</code>
     */
    public Builder addSpecialties(org.springframework.samples.petclinic.protobuf.ProtoSpecialty value) {
      if (specialtiesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSpecialtiesIsMutable();
        specialties_.add(value);
        onChanged();
      } else {
        specialtiesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoSpecialty specialties = 1;</code>
     */
    public Builder addSpecialties(
        int index, org.springframework.samples.petclinic.protobuf.ProtoSpecialty value) {
      if (specialtiesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSpecialtiesIsMutable();
        specialties_.add(index, value);
        onChanged();
      } else {
        specialtiesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoSpecialty specialties = 1;</code>
     */
    public Builder addSpecialties(
        org.springframework.samples.petclinic.protobuf.ProtoSpecialty.Builder builderForValue) {
      if (specialtiesBuilder_ == null) {
        ensureSpecialtiesIsMutable();
        specialties_.add(builderForValue.build());
        onChanged();
      } else {
        specialtiesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoSpecialty specialties = 1;</code>
     */
    public Builder addSpecialties(
        int index, org.springframework.samples.petclinic.protobuf.ProtoSpecialty.Builder builderForValue) {
      if (specialtiesBuilder_ == null) {
        ensureSpecialtiesIsMutable();
        specialties_.add(index, builderForValue.build());
        onChanged();
      } else {
        specialtiesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoSpecialty specialties = 1;</code>
     */
    public Builder addAllSpecialties(
        java.lang.Iterable<? extends org.springframework.samples.petclinic.protobuf.ProtoSpecialty> values) {
      if (specialtiesBuilder_ == null) {
        ensureSpecialtiesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, specialties_);
        onChanged();
      } else {
        specialtiesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoSpecialty specialties = 1;</code>
     */
    public Builder clearSpecialties() {
      if (specialtiesBuilder_ == null) {
        specialties_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        specialtiesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoSpecialty specialties = 1;</code>
     */
    public Builder removeSpecialties(int index) {
      if (specialtiesBuilder_ == null) {
        ensureSpecialtiesIsMutable();
        specialties_.remove(index);
        onChanged();
      } else {
        specialtiesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoSpecialty specialties = 1;</code>
     */
    public org.springframework.samples.petclinic.protobuf.ProtoSpecialty.Builder getSpecialtiesBuilder(
        int index) {
      return getSpecialtiesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoSpecialty specialties = 1;</code>
     */
    public org.springframework.samples.petclinic.protobuf.ProtoSpecialtyOrBuilder getSpecialtiesOrBuilder(
        int index) {
      if (specialtiesBuilder_ == null) {
        return specialties_.get(index);  } else {
        return specialtiesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoSpecialty specialties = 1;</code>
     */
    public java.util.List<? extends org.springframework.samples.petclinic.protobuf.ProtoSpecialtyOrBuilder> 
         getSpecialtiesOrBuilderList() {
      if (specialtiesBuilder_ != null) {
        return specialtiesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(specialties_);
      }
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoSpecialty specialties = 1;</code>
     */
    public org.springframework.samples.petclinic.protobuf.ProtoSpecialty.Builder addSpecialtiesBuilder() {
      return getSpecialtiesFieldBuilder().addBuilder(
          org.springframework.samples.petclinic.protobuf.ProtoSpecialty.getDefaultInstance());
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoSpecialty specialties = 1;</code>
     */
    public org.springframework.samples.petclinic.protobuf.ProtoSpecialty.Builder addSpecialtiesBuilder(
        int index) {
      return getSpecialtiesFieldBuilder().addBuilder(
          index, org.springframework.samples.petclinic.protobuf.ProtoSpecialty.getDefaultInstance());
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoSpecialty specialties = 1;</code>
     */
    public java.util.List<org.springframework.samples.petclinic.protobuf.ProtoSpecialty.Builder> 
         getSpecialtiesBuilderList() {
      return getSpecialtiesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.springframework.samples.petclinic.protobuf.ProtoSpecialty, org.springframework.samples.petclinic.protobuf.ProtoSpecialty.Builder, org.springframework.samples.petclinic.protobuf.ProtoSpecialtyOrBuilder> 
        getSpecialtiesFieldBuilder() {
      if (specialtiesBuilder_ == null) {
        specialtiesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.springframework.samples.petclinic.protobuf.ProtoSpecialty, org.springframework.samples.petclinic.protobuf.ProtoSpecialty.Builder, org.springframework.samples.petclinic.protobuf.ProtoSpecialtyOrBuilder>(
                specialties_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        specialties_ = null;
      }
      return specialtiesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.springframework.samples.petclinic.protobuf.ProtoSpecialties)
  }

  // @@protoc_insertion_point(class_scope:org.springframework.samples.petclinic.protobuf.ProtoSpecialties)
  private static final org.springframework.samples.petclinic.protobuf.ProtoSpecialties DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.springframework.samples.petclinic.protobuf.ProtoSpecialties();
  }

  public static org.springframework.samples.petclinic.protobuf.ProtoSpecialties getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProtoSpecialties>
      PARSER = new com.google.protobuf.AbstractParser<ProtoSpecialties>() {
    @java.lang.Override
    public ProtoSpecialties parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ProtoSpecialties> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProtoSpecialties> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.springframework.samples.petclinic.protobuf.ProtoSpecialties getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

