// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/petclinic.proto

// Protobuf Java Version: 3.25.3
package org.springframework.samples.petclinic.protobuf;

/**
 * Protobuf type {@code org.springframework.samples.petclinic.protobuf.ProtoPetTypes}
 */
public final class ProtoPetTypes extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.springframework.samples.petclinic.protobuf.ProtoPetTypes)
    ProtoPetTypesOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ProtoPetTypes.newBuilder() to construct.
  private ProtoPetTypes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProtoPetTypes() {
    petTypes_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ProtoPetTypes();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.springframework.samples.petclinic.protobuf.Petclinic.internal_static_org_springframework_samples_petclinic_protobuf_ProtoPetTypes_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.springframework.samples.petclinic.protobuf.Petclinic.internal_static_org_springframework_samples_petclinic_protobuf_ProtoPetTypes_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.springframework.samples.petclinic.protobuf.ProtoPetTypes.class, org.springframework.samples.petclinic.protobuf.ProtoPetTypes.Builder.class);
  }

  public static final int PETTYPES_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<org.springframework.samples.petclinic.protobuf.ProtoPetType> petTypes_;
  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPetType petTypes = 1;</code>
   */
  @java.lang.Override
  public java.util.List<org.springframework.samples.petclinic.protobuf.ProtoPetType> getPetTypesList() {
    return petTypes_;
  }
  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPetType petTypes = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.springframework.samples.petclinic.protobuf.ProtoPetTypeOrBuilder> 
      getPetTypesOrBuilderList() {
    return petTypes_;
  }
  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPetType petTypes = 1;</code>
   */
  @java.lang.Override
  public int getPetTypesCount() {
    return petTypes_.size();
  }
  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPetType petTypes = 1;</code>
   */
  @java.lang.Override
  public org.springframework.samples.petclinic.protobuf.ProtoPetType getPetTypes(int index) {
    return petTypes_.get(index);
  }
  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPetType petTypes = 1;</code>
   */
  @java.lang.Override
  public org.springframework.samples.petclinic.protobuf.ProtoPetTypeOrBuilder getPetTypesOrBuilder(
      int index) {
    return petTypes_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < petTypes_.size(); i++) {
      output.writeMessage(1, petTypes_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < petTypes_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, petTypes_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.springframework.samples.petclinic.protobuf.ProtoPetTypes)) {
      return super.equals(obj);
    }
    org.springframework.samples.petclinic.protobuf.ProtoPetTypes other = (org.springframework.samples.petclinic.protobuf.ProtoPetTypes) obj;

    if (!getPetTypesList()
        .equals(other.getPetTypesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getPetTypesCount() > 0) {
      hash = (37 * hash) + PETTYPES_FIELD_NUMBER;
      hash = (53 * hash) + getPetTypesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.springframework.samples.petclinic.protobuf.ProtoPetTypes parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.springframework.samples.petclinic.protobuf.ProtoPetTypes parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.springframework.samples.petclinic.protobuf.ProtoPetTypes parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.springframework.samples.petclinic.protobuf.ProtoPetTypes parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.springframework.samples.petclinic.protobuf.ProtoPetTypes parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.springframework.samples.petclinic.protobuf.ProtoPetTypes parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.springframework.samples.petclinic.protobuf.ProtoPetTypes parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.springframework.samples.petclinic.protobuf.ProtoPetTypes parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.springframework.samples.petclinic.protobuf.ProtoPetTypes parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.springframework.samples.petclinic.protobuf.ProtoPetTypes parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.springframework.samples.petclinic.protobuf.ProtoPetTypes parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.springframework.samples.petclinic.protobuf.ProtoPetTypes parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.springframework.samples.petclinic.protobuf.ProtoPetTypes prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.springframework.samples.petclinic.protobuf.ProtoPetTypes}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.springframework.samples.petclinic.protobuf.ProtoPetTypes)
      org.springframework.samples.petclinic.protobuf.ProtoPetTypesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.springframework.samples.petclinic.protobuf.Petclinic.internal_static_org_springframework_samples_petclinic_protobuf_ProtoPetTypes_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.springframework.samples.petclinic.protobuf.Petclinic.internal_static_org_springframework_samples_petclinic_protobuf_ProtoPetTypes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.springframework.samples.petclinic.protobuf.ProtoPetTypes.class, org.springframework.samples.petclinic.protobuf.ProtoPetTypes.Builder.class);
    }

    // Construct using org.springframework.samples.petclinic.protobuf.ProtoPetTypes.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (petTypesBuilder_ == null) {
        petTypes_ = java.util.Collections.emptyList();
      } else {
        petTypes_ = null;
        petTypesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.springframework.samples.petclinic.protobuf.Petclinic.internal_static_org_springframework_samples_petclinic_protobuf_ProtoPetTypes_descriptor;
    }

    @java.lang.Override
    public org.springframework.samples.petclinic.protobuf.ProtoPetTypes getDefaultInstanceForType() {
      return org.springframework.samples.petclinic.protobuf.ProtoPetTypes.getDefaultInstance();
    }

    @java.lang.Override
    public org.springframework.samples.petclinic.protobuf.ProtoPetTypes build() {
      org.springframework.samples.petclinic.protobuf.ProtoPetTypes result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.springframework.samples.petclinic.protobuf.ProtoPetTypes buildPartial() {
      org.springframework.samples.petclinic.protobuf.ProtoPetTypes result = new org.springframework.samples.petclinic.protobuf.ProtoPetTypes(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(org.springframework.samples.petclinic.protobuf.ProtoPetTypes result) {
      if (petTypesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          petTypes_ = java.util.Collections.unmodifiableList(petTypes_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.petTypes_ = petTypes_;
      } else {
        result.petTypes_ = petTypesBuilder_.build();
      }
    }

    private void buildPartial0(org.springframework.samples.petclinic.protobuf.ProtoPetTypes result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.springframework.samples.petclinic.protobuf.ProtoPetTypes) {
        return mergeFrom((org.springframework.samples.petclinic.protobuf.ProtoPetTypes)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.springframework.samples.petclinic.protobuf.ProtoPetTypes other) {
      if (other == org.springframework.samples.petclinic.protobuf.ProtoPetTypes.getDefaultInstance()) return this;
      if (petTypesBuilder_ == null) {
        if (!other.petTypes_.isEmpty()) {
          if (petTypes_.isEmpty()) {
            petTypes_ = other.petTypes_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePetTypesIsMutable();
            petTypes_.addAll(other.petTypes_);
          }
          onChanged();
        }
      } else {
        if (!other.petTypes_.isEmpty()) {
          if (petTypesBuilder_.isEmpty()) {
            petTypesBuilder_.dispose();
            petTypesBuilder_ = null;
            petTypes_ = other.petTypes_;
            bitField0_ = (bitField0_ & ~0x00000001);
            petTypesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPetTypesFieldBuilder() : null;
          } else {
            petTypesBuilder_.addAllMessages(other.petTypes_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              org.springframework.samples.petclinic.protobuf.ProtoPetType m =
                  input.readMessage(
                      org.springframework.samples.petclinic.protobuf.ProtoPetType.parser(),
                      extensionRegistry);
              if (petTypesBuilder_ == null) {
                ensurePetTypesIsMutable();
                petTypes_.add(m);
              } else {
                petTypesBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<org.springframework.samples.petclinic.protobuf.ProtoPetType> petTypes_ =
      java.util.Collections.emptyList();
    private void ensurePetTypesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        petTypes_ = new java.util.ArrayList<org.springframework.samples.petclinic.protobuf.ProtoPetType>(petTypes_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.springframework.samples.petclinic.protobuf.ProtoPetType, org.springframework.samples.petclinic.protobuf.ProtoPetType.Builder, org.springframework.samples.petclinic.protobuf.ProtoPetTypeOrBuilder> petTypesBuilder_;

    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPetType petTypes = 1;</code>
     */
    public java.util.List<org.springframework.samples.petclinic.protobuf.ProtoPetType> getPetTypesList() {
      if (petTypesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(petTypes_);
      } else {
        return petTypesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPetType petTypes = 1;</code>
     */
    public int getPetTypesCount() {
      if (petTypesBuilder_ == null) {
        return petTypes_.size();
      } else {
        return petTypesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPetType petTypes = 1;</code>
     */
    public org.springframework.samples.petclinic.protobuf.ProtoPetType getPetTypes(int index) {
      if (petTypesBuilder_ == null) {
        return petTypes_.get(index);
      } else {
        return petTypesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPetType petTypes = 1;</code>
     */
    public Builder setPetTypes(
        int index, org.springframework.samples.petclinic.protobuf.ProtoPetType value) {
      if (petTypesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePetTypesIsMutable();
        petTypes_.set(index, value);
        onChanged();
      } else {
        petTypesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPetType petTypes = 1;</code>
     */
    public Builder setPetTypes(
        int index, org.springframework.samples.petclinic.protobuf.ProtoPetType.Builder builderForValue) {
      if (petTypesBuilder_ == null) {
        ensurePetTypesIsMutable();
        petTypes_.set(index, builderForValue.build());
        onChanged();
      } else {
        petTypesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPetType petTypes = 1;</code>
     */
    public Builder addPetTypes(org.springframework.samples.petclinic.protobuf.ProtoPetType value) {
      if (petTypesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePetTypesIsMutable();
        petTypes_.add(value);
        onChanged();
      } else {
        petTypesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPetType petTypes = 1;</code>
     */
    public Builder addPetTypes(
        int index, org.springframework.samples.petclinic.protobuf.ProtoPetType value) {
      if (petTypesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePetTypesIsMutable();
        petTypes_.add(index, value);
        onChanged();
      } else {
        petTypesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPetType petTypes = 1;</code>
     */
    public Builder addPetTypes(
        org.springframework.samples.petclinic.protobuf.ProtoPetType.Builder builderForValue) {
      if (petTypesBuilder_ == null) {
        ensurePetTypesIsMutable();
        petTypes_.add(builderForValue.build());
        onChanged();
      } else {
        petTypesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPetType petTypes = 1;</code>
     */
    public Builder addPetTypes(
        int index, org.springframework.samples.petclinic.protobuf.ProtoPetType.Builder builderForValue) {
      if (petTypesBuilder_ == null) {
        ensurePetTypesIsMutable();
        petTypes_.add(index, builderForValue.build());
        onChanged();
      } else {
        petTypesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPetType petTypes = 1;</code>
     */
    public Builder addAllPetTypes(
        java.lang.Iterable<? extends org.springframework.samples.petclinic.protobuf.ProtoPetType> values) {
      if (petTypesBuilder_ == null) {
        ensurePetTypesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, petTypes_);
        onChanged();
      } else {
        petTypesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPetType petTypes = 1;</code>
     */
    public Builder clearPetTypes() {
      if (petTypesBuilder_ == null) {
        petTypes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        petTypesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPetType petTypes = 1;</code>
     */
    public Builder removePetTypes(int index) {
      if (petTypesBuilder_ == null) {
        ensurePetTypesIsMutable();
        petTypes_.remove(index);
        onChanged();
      } else {
        petTypesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPetType petTypes = 1;</code>
     */
    public org.springframework.samples.petclinic.protobuf.ProtoPetType.Builder getPetTypesBuilder(
        int index) {
      return getPetTypesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPetType petTypes = 1;</code>
     */
    public org.springframework.samples.petclinic.protobuf.ProtoPetTypeOrBuilder getPetTypesOrBuilder(
        int index) {
      if (petTypesBuilder_ == null) {
        return petTypes_.get(index);  } else {
        return petTypesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPetType petTypes = 1;</code>
     */
    public java.util.List<? extends org.springframework.samples.petclinic.protobuf.ProtoPetTypeOrBuilder> 
         getPetTypesOrBuilderList() {
      if (petTypesBuilder_ != null) {
        return petTypesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(petTypes_);
      }
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPetType petTypes = 1;</code>
     */
    public org.springframework.samples.petclinic.protobuf.ProtoPetType.Builder addPetTypesBuilder() {
      return getPetTypesFieldBuilder().addBuilder(
          org.springframework.samples.petclinic.protobuf.ProtoPetType.getDefaultInstance());
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPetType petTypes = 1;</code>
     */
    public org.springframework.samples.petclinic.protobuf.ProtoPetType.Builder addPetTypesBuilder(
        int index) {
      return getPetTypesFieldBuilder().addBuilder(
          index, org.springframework.samples.petclinic.protobuf.ProtoPetType.getDefaultInstance());
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPetType petTypes = 1;</code>
     */
    public java.util.List<org.springframework.samples.petclinic.protobuf.ProtoPetType.Builder> 
         getPetTypesBuilderList() {
      return getPetTypesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.springframework.samples.petclinic.protobuf.ProtoPetType, org.springframework.samples.petclinic.protobuf.ProtoPetType.Builder, org.springframework.samples.petclinic.protobuf.ProtoPetTypeOrBuilder> 
        getPetTypesFieldBuilder() {
      if (petTypesBuilder_ == null) {
        petTypesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.springframework.samples.petclinic.protobuf.ProtoPetType, org.springframework.samples.petclinic.protobuf.ProtoPetType.Builder, org.springframework.samples.petclinic.protobuf.ProtoPetTypeOrBuilder>(
                petTypes_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        petTypes_ = null;
      }
      return petTypesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.springframework.samples.petclinic.protobuf.ProtoPetTypes)
  }

  // @@protoc_insertion_point(class_scope:org.springframework.samples.petclinic.protobuf.ProtoPetTypes)
  private static final org.springframework.samples.petclinic.protobuf.ProtoPetTypes DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.springframework.samples.petclinic.protobuf.ProtoPetTypes();
  }

  public static org.springframework.samples.petclinic.protobuf.ProtoPetTypes getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProtoPetTypes>
      PARSER = new com.google.protobuf.AbstractParser<ProtoPetTypes>() {
    @java.lang.Override
    public ProtoPetTypes parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ProtoPetTypes> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProtoPetTypes> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.springframework.samples.petclinic.protobuf.ProtoPetTypes getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

