// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/petclinic.proto

// Protobuf Java Version: 3.25.3
package org.springframework.samples.petclinic.protobuf;

/**
 * Protobuf type {@code org.springframework.samples.petclinic.protobuf.ProtoPets}
 */
public final class ProtoPets extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.springframework.samples.petclinic.protobuf.ProtoPets)
    ProtoPetsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ProtoPets.newBuilder() to construct.
  private ProtoPets(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProtoPets() {
    pets_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ProtoPets();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.springframework.samples.petclinic.protobuf.Petclinic.internal_static_org_springframework_samples_petclinic_protobuf_ProtoPets_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.springframework.samples.petclinic.protobuf.Petclinic.internal_static_org_springframework_samples_petclinic_protobuf_ProtoPets_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.springframework.samples.petclinic.protobuf.ProtoPets.class, org.springframework.samples.petclinic.protobuf.ProtoPets.Builder.class);
  }

  public static final int PETS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<org.springframework.samples.petclinic.protobuf.ProtoPet> pets_;
  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPet pets = 1;</code>
   */
  @java.lang.Override
  public java.util.List<org.springframework.samples.petclinic.protobuf.ProtoPet> getPetsList() {
    return pets_;
  }
  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPet pets = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.springframework.samples.petclinic.protobuf.ProtoPetOrBuilder> 
      getPetsOrBuilderList() {
    return pets_;
  }
  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPet pets = 1;</code>
   */
  @java.lang.Override
  public int getPetsCount() {
    return pets_.size();
  }
  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPet pets = 1;</code>
   */
  @java.lang.Override
  public org.springframework.samples.petclinic.protobuf.ProtoPet getPets(int index) {
    return pets_.get(index);
  }
  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPet pets = 1;</code>
   */
  @java.lang.Override
  public org.springframework.samples.petclinic.protobuf.ProtoPetOrBuilder getPetsOrBuilder(
      int index) {
    return pets_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < pets_.size(); i++) {
      output.writeMessage(1, pets_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < pets_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, pets_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.springframework.samples.petclinic.protobuf.ProtoPets)) {
      return super.equals(obj);
    }
    org.springframework.samples.petclinic.protobuf.ProtoPets other = (org.springframework.samples.petclinic.protobuf.ProtoPets) obj;

    if (!getPetsList()
        .equals(other.getPetsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getPetsCount() > 0) {
      hash = (37 * hash) + PETS_FIELD_NUMBER;
      hash = (53 * hash) + getPetsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.springframework.samples.petclinic.protobuf.ProtoPets parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.springframework.samples.petclinic.protobuf.ProtoPets parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.springframework.samples.petclinic.protobuf.ProtoPets parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.springframework.samples.petclinic.protobuf.ProtoPets parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.springframework.samples.petclinic.protobuf.ProtoPets parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.springframework.samples.petclinic.protobuf.ProtoPets parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.springframework.samples.petclinic.protobuf.ProtoPets parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.springframework.samples.petclinic.protobuf.ProtoPets parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.springframework.samples.petclinic.protobuf.ProtoPets parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.springframework.samples.petclinic.protobuf.ProtoPets parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.springframework.samples.petclinic.protobuf.ProtoPets parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.springframework.samples.petclinic.protobuf.ProtoPets parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.springframework.samples.petclinic.protobuf.ProtoPets prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.springframework.samples.petclinic.protobuf.ProtoPets}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.springframework.samples.petclinic.protobuf.ProtoPets)
      org.springframework.samples.petclinic.protobuf.ProtoPetsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.springframework.samples.petclinic.protobuf.Petclinic.internal_static_org_springframework_samples_petclinic_protobuf_ProtoPets_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.springframework.samples.petclinic.protobuf.Petclinic.internal_static_org_springframework_samples_petclinic_protobuf_ProtoPets_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.springframework.samples.petclinic.protobuf.ProtoPets.class, org.springframework.samples.petclinic.protobuf.ProtoPets.Builder.class);
    }

    // Construct using org.springframework.samples.petclinic.protobuf.ProtoPets.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (petsBuilder_ == null) {
        pets_ = java.util.Collections.emptyList();
      } else {
        pets_ = null;
        petsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.springframework.samples.petclinic.protobuf.Petclinic.internal_static_org_springframework_samples_petclinic_protobuf_ProtoPets_descriptor;
    }

    @java.lang.Override
    public org.springframework.samples.petclinic.protobuf.ProtoPets getDefaultInstanceForType() {
      return org.springframework.samples.petclinic.protobuf.ProtoPets.getDefaultInstance();
    }

    @java.lang.Override
    public org.springframework.samples.petclinic.protobuf.ProtoPets build() {
      org.springframework.samples.petclinic.protobuf.ProtoPets result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.springframework.samples.petclinic.protobuf.ProtoPets buildPartial() {
      org.springframework.samples.petclinic.protobuf.ProtoPets result = new org.springframework.samples.petclinic.protobuf.ProtoPets(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(org.springframework.samples.petclinic.protobuf.ProtoPets result) {
      if (petsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          pets_ = java.util.Collections.unmodifiableList(pets_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.pets_ = pets_;
      } else {
        result.pets_ = petsBuilder_.build();
      }
    }

    private void buildPartial0(org.springframework.samples.petclinic.protobuf.ProtoPets result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.springframework.samples.petclinic.protobuf.ProtoPets) {
        return mergeFrom((org.springframework.samples.petclinic.protobuf.ProtoPets)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.springframework.samples.petclinic.protobuf.ProtoPets other) {
      if (other == org.springframework.samples.petclinic.protobuf.ProtoPets.getDefaultInstance()) return this;
      if (petsBuilder_ == null) {
        if (!other.pets_.isEmpty()) {
          if (pets_.isEmpty()) {
            pets_ = other.pets_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePetsIsMutable();
            pets_.addAll(other.pets_);
          }
          onChanged();
        }
      } else {
        if (!other.pets_.isEmpty()) {
          if (petsBuilder_.isEmpty()) {
            petsBuilder_.dispose();
            petsBuilder_ = null;
            pets_ = other.pets_;
            bitField0_ = (bitField0_ & ~0x00000001);
            petsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPetsFieldBuilder() : null;
          } else {
            petsBuilder_.addAllMessages(other.pets_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              org.springframework.samples.petclinic.protobuf.ProtoPet m =
                  input.readMessage(
                      org.springframework.samples.petclinic.protobuf.ProtoPet.parser(),
                      extensionRegistry);
              if (petsBuilder_ == null) {
                ensurePetsIsMutable();
                pets_.add(m);
              } else {
                petsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<org.springframework.samples.petclinic.protobuf.ProtoPet> pets_ =
      java.util.Collections.emptyList();
    private void ensurePetsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        pets_ = new java.util.ArrayList<org.springframework.samples.petclinic.protobuf.ProtoPet>(pets_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.springframework.samples.petclinic.protobuf.ProtoPet, org.springframework.samples.petclinic.protobuf.ProtoPet.Builder, org.springframework.samples.petclinic.protobuf.ProtoPetOrBuilder> petsBuilder_;

    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPet pets = 1;</code>
     */
    public java.util.List<org.springframework.samples.petclinic.protobuf.ProtoPet> getPetsList() {
      if (petsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(pets_);
      } else {
        return petsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPet pets = 1;</code>
     */
    public int getPetsCount() {
      if (petsBuilder_ == null) {
        return pets_.size();
      } else {
        return petsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPet pets = 1;</code>
     */
    public org.springframework.samples.petclinic.protobuf.ProtoPet getPets(int index) {
      if (petsBuilder_ == null) {
        return pets_.get(index);
      } else {
        return petsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPet pets = 1;</code>
     */
    public Builder setPets(
        int index, org.springframework.samples.petclinic.protobuf.ProtoPet value) {
      if (petsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePetsIsMutable();
        pets_.set(index, value);
        onChanged();
      } else {
        petsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPet pets = 1;</code>
     */
    public Builder setPets(
        int index, org.springframework.samples.petclinic.protobuf.ProtoPet.Builder builderForValue) {
      if (petsBuilder_ == null) {
        ensurePetsIsMutable();
        pets_.set(index, builderForValue.build());
        onChanged();
      } else {
        petsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPet pets = 1;</code>
     */
    public Builder addPets(org.springframework.samples.petclinic.protobuf.ProtoPet value) {
      if (petsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePetsIsMutable();
        pets_.add(value);
        onChanged();
      } else {
        petsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPet pets = 1;</code>
     */
    public Builder addPets(
        int index, org.springframework.samples.petclinic.protobuf.ProtoPet value) {
      if (petsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePetsIsMutable();
        pets_.add(index, value);
        onChanged();
      } else {
        petsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPet pets = 1;</code>
     */
    public Builder addPets(
        org.springframework.samples.petclinic.protobuf.ProtoPet.Builder builderForValue) {
      if (petsBuilder_ == null) {
        ensurePetsIsMutable();
        pets_.add(builderForValue.build());
        onChanged();
      } else {
        petsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPet pets = 1;</code>
     */
    public Builder addPets(
        int index, org.springframework.samples.petclinic.protobuf.ProtoPet.Builder builderForValue) {
      if (petsBuilder_ == null) {
        ensurePetsIsMutable();
        pets_.add(index, builderForValue.build());
        onChanged();
      } else {
        petsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPet pets = 1;</code>
     */
    public Builder addAllPets(
        java.lang.Iterable<? extends org.springframework.samples.petclinic.protobuf.ProtoPet> values) {
      if (petsBuilder_ == null) {
        ensurePetsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, pets_);
        onChanged();
      } else {
        petsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPet pets = 1;</code>
     */
    public Builder clearPets() {
      if (petsBuilder_ == null) {
        pets_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        petsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPet pets = 1;</code>
     */
    public Builder removePets(int index) {
      if (petsBuilder_ == null) {
        ensurePetsIsMutable();
        pets_.remove(index);
        onChanged();
      } else {
        petsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPet pets = 1;</code>
     */
    public org.springframework.samples.petclinic.protobuf.ProtoPet.Builder getPetsBuilder(
        int index) {
      return getPetsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPet pets = 1;</code>
     */
    public org.springframework.samples.petclinic.protobuf.ProtoPetOrBuilder getPetsOrBuilder(
        int index) {
      if (petsBuilder_ == null) {
        return pets_.get(index);  } else {
        return petsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPet pets = 1;</code>
     */
    public java.util.List<? extends org.springframework.samples.petclinic.protobuf.ProtoPetOrBuilder> 
         getPetsOrBuilderList() {
      if (petsBuilder_ != null) {
        return petsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(pets_);
      }
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPet pets = 1;</code>
     */
    public org.springframework.samples.petclinic.protobuf.ProtoPet.Builder addPetsBuilder() {
      return getPetsFieldBuilder().addBuilder(
          org.springframework.samples.petclinic.protobuf.ProtoPet.getDefaultInstance());
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPet pets = 1;</code>
     */
    public org.springframework.samples.petclinic.protobuf.ProtoPet.Builder addPetsBuilder(
        int index) {
      return getPetsFieldBuilder().addBuilder(
          index, org.springframework.samples.petclinic.protobuf.ProtoPet.getDefaultInstance());
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPet pets = 1;</code>
     */
    public java.util.List<org.springframework.samples.petclinic.protobuf.ProtoPet.Builder> 
         getPetsBuilderList() {
      return getPetsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.springframework.samples.petclinic.protobuf.ProtoPet, org.springframework.samples.petclinic.protobuf.ProtoPet.Builder, org.springframework.samples.petclinic.protobuf.ProtoPetOrBuilder> 
        getPetsFieldBuilder() {
      if (petsBuilder_ == null) {
        petsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.springframework.samples.petclinic.protobuf.ProtoPet, org.springframework.samples.petclinic.protobuf.ProtoPet.Builder, org.springframework.samples.petclinic.protobuf.ProtoPetOrBuilder>(
                pets_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        pets_ = null;
      }
      return petsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.springframework.samples.petclinic.protobuf.ProtoPets)
  }

  // @@protoc_insertion_point(class_scope:org.springframework.samples.petclinic.protobuf.ProtoPets)
  private static final org.springframework.samples.petclinic.protobuf.ProtoPets DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.springframework.samples.petclinic.protobuf.ProtoPets();
  }

  public static org.springframework.samples.petclinic.protobuf.ProtoPets getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProtoPets>
      PARSER = new com.google.protobuf.AbstractParser<ProtoPets>() {
    @java.lang.Override
    public ProtoPets parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ProtoPets> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProtoPets> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.springframework.samples.petclinic.protobuf.ProtoPets getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

