// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/petclinic.proto

// Protobuf Java Version: 3.25.3
package org.springframework.samples.petclinic.protobuf;

public interface ProtoOwnerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.springframework.samples.petclinic.protobuf.ProtoOwner)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string first_name = 2;</code>
   * @return The firstName.
   */
  java.lang.String getFirstName();
  /**
   * <code>string first_name = 2;</code>
   * @return The bytes for firstName.
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string last_name = 3;</code>
   * @return The lastName.
   */
  java.lang.String getLastName();
  /**
   * <code>string last_name = 3;</code>
   * @return The bytes for lastName.
   */
  com.google.protobuf.ByteString
      getLastNameBytes();

  /**
   * <code>string address = 4;</code>
   * @return The address.
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 4;</code>
   * @return The bytes for address.
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>string city = 5;</code>
   * @return The city.
   */
  java.lang.String getCity();
  /**
   * <code>string city = 5;</code>
   * @return The bytes for city.
   */
  com.google.protobuf.ByteString
      getCityBytes();

  /**
   * <code>string telephone = 6;</code>
   * @return The telephone.
   */
  java.lang.String getTelephone();
  /**
   * <code>string telephone = 6;</code>
   * @return The bytes for telephone.
   */
  com.google.protobuf.ByteString
      getTelephoneBytes();

  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPet pets = 7;</code>
   */
  java.util.List<org.springframework.samples.petclinic.protobuf.ProtoPet> 
      getPetsList();
  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPet pets = 7;</code>
   */
  org.springframework.samples.petclinic.protobuf.ProtoPet getPets(int index);
  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPet pets = 7;</code>
   */
  int getPetsCount();
  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPet pets = 7;</code>
   */
  java.util.List<? extends org.springframework.samples.petclinic.protobuf.ProtoPetOrBuilder> 
      getPetsOrBuilderList();
  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPet pets = 7;</code>
   */
  org.springframework.samples.petclinic.protobuf.ProtoPetOrBuilder getPetsOrBuilder(
      int index);
}
