// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/petclinic.proto

// Protobuf Java Version: 3.25.3
package org.springframework.samples.petclinic.protobuf;

public interface ProtoOwnerAddPetOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.springframework.samples.petclinic.protobuf.ProtoOwnerAddPet)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string birth_date = 2;</code>
   * @return The birthDate.
   */
  java.lang.String getBirthDate();
  /**
   * <code>string birth_date = 2;</code>
   * @return The bytes for birthDate.
   */
  com.google.protobuf.ByteString
      getBirthDateBytes();

  /**
   * <code>.org.springframework.samples.petclinic.protobuf.ProtoPetType type = 3;</code>
   * @return Whether the type field is set.
   */
  boolean hasType();
  /**
   * <code>.org.springframework.samples.petclinic.protobuf.ProtoPetType type = 3;</code>
   * @return The type.
   */
  org.springframework.samples.petclinic.protobuf.ProtoPetType getType();
  /**
   * <code>.org.springframework.samples.petclinic.protobuf.ProtoPetType type = 3;</code>
   */
  org.springframework.samples.petclinic.protobuf.ProtoPetTypeOrBuilder getTypeOrBuilder();
}
