// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/petclinic.proto

// Protobuf Java Version: 3.25.3
package org.springframework.samples.petclinic.protobuf;

public interface ProtoPetsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.springframework.samples.petclinic.protobuf.ProtoPets)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPet pets = 1;</code>
   */
  java.util.List<org.springframework.samples.petclinic.protobuf.ProtoPet> 
      getPetsList();
  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPet pets = 1;</code>
   */
  org.springframework.samples.petclinic.protobuf.ProtoPet getPets(int index);
  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPet pets = 1;</code>
   */
  int getPetsCount();
  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPet pets = 1;</code>
   */
  java.util.List<? extends org.springframework.samples.petclinic.protobuf.ProtoPetOrBuilder> 
      getPetsOrBuilderList();
  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPet pets = 1;</code>
   */
  org.springframework.samples.petclinic.protobuf.ProtoPetOrBuilder getPetsOrBuilder(
      int index);
}
