// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/petclinic.proto

// Protobuf Java Version: 3.25.3
package org.springframework.samples.petclinic.protobuf;

/**
 * Protobuf type {@code org.springframework.samples.petclinic.protobuf.ProtoPetAdd}
 */
public final class ProtoPetAdd extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.springframework.samples.petclinic.protobuf.ProtoPetAdd)
    ProtoPetAddOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ProtoPetAdd.newBuilder() to construct.
  private ProtoPetAdd(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProtoPetAdd() {
    name_ = "";
    birthDate_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ProtoPetAdd();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.springframework.samples.petclinic.protobuf.Petclinic.internal_static_org_springframework_samples_petclinic_protobuf_ProtoPetAdd_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.springframework.samples.petclinic.protobuf.Petclinic.internal_static_org_springframework_samples_petclinic_protobuf_ProtoPetAdd_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.springframework.samples.petclinic.protobuf.ProtoPetAdd.class, org.springframework.samples.petclinic.protobuf.ProtoPetAdd.Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BIRTH_DATE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object birthDate_ = "";
  /**
   * <code>string birth_date = 2;</code>
   * @return The birthDate.
   */
  @java.lang.Override
  public java.lang.String getBirthDate() {
    java.lang.Object ref = birthDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      birthDate_ = s;
      return s;
    }
  }
  /**
   * <code>string birth_date = 2;</code>
   * @return The bytes for birthDate.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBirthDateBytes() {
    java.lang.Object ref = birthDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      birthDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PET_TYPE_ID_FIELD_NUMBER = 3;
  private int petTypeId_ = 0;
  /**
   * <code>int32 pet_type_id = 3;</code>
   * @return The petTypeId.
   */
  @java.lang.Override
  public int getPetTypeId() {
    return petTypeId_;
  }

  public static final int OWNER_ID_FIELD_NUMBER = 4;
  private int ownerId_ = 0;
  /**
   * <code>int32 owner_id = 4;</code>
   * @return The ownerId.
   */
  @java.lang.Override
  public int getOwnerId() {
    return ownerId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(birthDate_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, birthDate_);
    }
    if (petTypeId_ != 0) {
      output.writeInt32(3, petTypeId_);
    }
    if (ownerId_ != 0) {
      output.writeInt32(4, ownerId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(birthDate_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, birthDate_);
    }
    if (petTypeId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, petTypeId_);
    }
    if (ownerId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, ownerId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.springframework.samples.petclinic.protobuf.ProtoPetAdd)) {
      return super.equals(obj);
    }
    org.springframework.samples.petclinic.protobuf.ProtoPetAdd other = (org.springframework.samples.petclinic.protobuf.ProtoPetAdd) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (!getBirthDate()
        .equals(other.getBirthDate())) return false;
    if (getPetTypeId()
        != other.getPetTypeId()) return false;
    if (getOwnerId()
        != other.getOwnerId()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + BIRTH_DATE_FIELD_NUMBER;
    hash = (53 * hash) + getBirthDate().hashCode();
    hash = (37 * hash) + PET_TYPE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getPetTypeId();
    hash = (37 * hash) + OWNER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getOwnerId();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.springframework.samples.petclinic.protobuf.ProtoPetAdd parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.springframework.samples.petclinic.protobuf.ProtoPetAdd parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.springframework.samples.petclinic.protobuf.ProtoPetAdd parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.springframework.samples.petclinic.protobuf.ProtoPetAdd parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.springframework.samples.petclinic.protobuf.ProtoPetAdd parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.springframework.samples.petclinic.protobuf.ProtoPetAdd parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.springframework.samples.petclinic.protobuf.ProtoPetAdd parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.springframework.samples.petclinic.protobuf.ProtoPetAdd parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.springframework.samples.petclinic.protobuf.ProtoPetAdd parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.springframework.samples.petclinic.protobuf.ProtoPetAdd parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.springframework.samples.petclinic.protobuf.ProtoPetAdd parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.springframework.samples.petclinic.protobuf.ProtoPetAdd parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.springframework.samples.petclinic.protobuf.ProtoPetAdd prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.springframework.samples.petclinic.protobuf.ProtoPetAdd}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.springframework.samples.petclinic.protobuf.ProtoPetAdd)
      org.springframework.samples.petclinic.protobuf.ProtoPetAddOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.springframework.samples.petclinic.protobuf.Petclinic.internal_static_org_springframework_samples_petclinic_protobuf_ProtoPetAdd_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.springframework.samples.petclinic.protobuf.Petclinic.internal_static_org_springframework_samples_petclinic_protobuf_ProtoPetAdd_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.springframework.samples.petclinic.protobuf.ProtoPetAdd.class, org.springframework.samples.petclinic.protobuf.ProtoPetAdd.Builder.class);
    }

    // Construct using org.springframework.samples.petclinic.protobuf.ProtoPetAdd.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      name_ = "";
      birthDate_ = "";
      petTypeId_ = 0;
      ownerId_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.springframework.samples.petclinic.protobuf.Petclinic.internal_static_org_springframework_samples_petclinic_protobuf_ProtoPetAdd_descriptor;
    }

    @java.lang.Override
    public org.springframework.samples.petclinic.protobuf.ProtoPetAdd getDefaultInstanceForType() {
      return org.springframework.samples.petclinic.protobuf.ProtoPetAdd.getDefaultInstance();
    }

    @java.lang.Override
    public org.springframework.samples.petclinic.protobuf.ProtoPetAdd build() {
      org.springframework.samples.petclinic.protobuf.ProtoPetAdd result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.springframework.samples.petclinic.protobuf.ProtoPetAdd buildPartial() {
      org.springframework.samples.petclinic.protobuf.ProtoPetAdd result = new org.springframework.samples.petclinic.protobuf.ProtoPetAdd(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.springframework.samples.petclinic.protobuf.ProtoPetAdd result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.birthDate_ = birthDate_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.petTypeId_ = petTypeId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.ownerId_ = ownerId_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.springframework.samples.petclinic.protobuf.ProtoPetAdd) {
        return mergeFrom((org.springframework.samples.petclinic.protobuf.ProtoPetAdd)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.springframework.samples.petclinic.protobuf.ProtoPetAdd other) {
      if (other == org.springframework.samples.petclinic.protobuf.ProtoPetAdd.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getBirthDate().isEmpty()) {
        birthDate_ = other.birthDate_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getPetTypeId() != 0) {
        setPetTypeId(other.getPetTypeId());
      }
      if (other.getOwnerId() != 0) {
        setOwnerId(other.getOwnerId());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              birthDate_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              petTypeId_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              ownerId_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object birthDate_ = "";
    /**
     * <code>string birth_date = 2;</code>
     * @return The birthDate.
     */
    public java.lang.String getBirthDate() {
      java.lang.Object ref = birthDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        birthDate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string birth_date = 2;</code>
     * @return The bytes for birthDate.
     */
    public com.google.protobuf.ByteString
        getBirthDateBytes() {
      java.lang.Object ref = birthDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        birthDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string birth_date = 2;</code>
     * @param value The birthDate to set.
     * @return This builder for chaining.
     */
    public Builder setBirthDate(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      birthDate_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string birth_date = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearBirthDate() {
      birthDate_ = getDefaultInstance().getBirthDate();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string birth_date = 2;</code>
     * @param value The bytes for birthDate to set.
     * @return This builder for chaining.
     */
    public Builder setBirthDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      birthDate_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int petTypeId_ ;
    /**
     * <code>int32 pet_type_id = 3;</code>
     * @return The petTypeId.
     */
    @java.lang.Override
    public int getPetTypeId() {
      return petTypeId_;
    }
    /**
     * <code>int32 pet_type_id = 3;</code>
     * @param value The petTypeId to set.
     * @return This builder for chaining.
     */
    public Builder setPetTypeId(int value) {

      petTypeId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 pet_type_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPetTypeId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      petTypeId_ = 0;
      onChanged();
      return this;
    }

    private int ownerId_ ;
    /**
     * <code>int32 owner_id = 4;</code>
     * @return The ownerId.
     */
    @java.lang.Override
    public int getOwnerId() {
      return ownerId_;
    }
    /**
     * <code>int32 owner_id = 4;</code>
     * @param value The ownerId to set.
     * @return This builder for chaining.
     */
    public Builder setOwnerId(int value) {

      ownerId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 owner_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearOwnerId() {
      bitField0_ = (bitField0_ & ~0x00000008);
      ownerId_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.springframework.samples.petclinic.protobuf.ProtoPetAdd)
  }

  // @@protoc_insertion_point(class_scope:org.springframework.samples.petclinic.protobuf.ProtoPetAdd)
  private static final org.springframework.samples.petclinic.protobuf.ProtoPetAdd DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.springframework.samples.petclinic.protobuf.ProtoPetAdd();
  }

  public static org.springframework.samples.petclinic.protobuf.ProtoPetAdd getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProtoPetAdd>
      PARSER = new com.google.protobuf.AbstractParser<ProtoPetAdd>() {
    @java.lang.Override
    public ProtoPetAdd parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ProtoPetAdd> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProtoPetAdd> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.springframework.samples.petclinic.protobuf.ProtoPetAdd getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

