// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/petclinic.proto

// Protobuf Java Version: 3.25.3
package org.springframework.samples.petclinic.protobuf;

public interface ProtoVisitsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.springframework.samples.petclinic.protobuf.ProtoVisits)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoVisit visits = 1;</code>
   */
  java.util.List<org.springframework.samples.petclinic.protobuf.ProtoVisit> 
      getVisitsList();
  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoVisit visits = 1;</code>
   */
  org.springframework.samples.petclinic.protobuf.ProtoVisit getVisits(int index);
  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoVisit visits = 1;</code>
   */
  int getVisitsCount();
  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoVisit visits = 1;</code>
   */
  java.util.List<? extends org.springframework.samples.petclinic.protobuf.ProtoVisitOrBuilder> 
      getVisitsOrBuilderList();
  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoVisit visits = 1;</code>
   */
  org.springframework.samples.petclinic.protobuf.ProtoVisitOrBuilder getVisitsOrBuilder(
      int index);
}
