// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/petclinic.proto

// Protobuf Java Version: 3.25.3
package org.springframework.samples.petclinic.protobuf;

/**
 * Protobuf type {@code org.springframework.samples.petclinic.protobuf.ProtoPet}
 */
public final class ProtoPet extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.springframework.samples.petclinic.protobuf.ProtoPet)
    ProtoPetOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ProtoPet.newBuilder() to construct.
  private ProtoPet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProtoPet() {
    name_ = "";
    birthDate_ = "";
    petType_ = "";
    visits_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ProtoPet();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.springframework.samples.petclinic.protobuf.Petclinic.internal_static_org_springframework_samples_petclinic_protobuf_ProtoPet_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.springframework.samples.petclinic.protobuf.Petclinic.internal_static_org_springframework_samples_petclinic_protobuf_ProtoPet_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.springframework.samples.petclinic.protobuf.ProtoPet.class, org.springframework.samples.petclinic.protobuf.ProtoPet.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private int id_ = 0;
  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public int getId() {
    return id_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BIRTH_DATE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object birthDate_ = "";
  /**
   * <code>string birth_date = 3;</code>
   * @return The birthDate.
   */
  @java.lang.Override
  public java.lang.String getBirthDate() {
    java.lang.Object ref = birthDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      birthDate_ = s;
      return s;
    }
  }
  /**
   * <code>string birth_date = 3;</code>
   * @return The bytes for birthDate.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBirthDateBytes() {
    java.lang.Object ref = birthDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      birthDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PET_TYPE_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object petType_ = "";
  /**
   * <code>string pet_type = 4;</code>
   * @return The petType.
   */
  @java.lang.Override
  public java.lang.String getPetType() {
    java.lang.Object ref = petType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      petType_ = s;
      return s;
    }
  }
  /**
   * <code>string pet_type = 4;</code>
   * @return The bytes for petType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPetTypeBytes() {
    java.lang.Object ref = petType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      petType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OWNER_FIELD_NUMBER = 5;
  private org.springframework.samples.petclinic.protobuf.ProtoPetOwner owner_;
  /**
   * <code>.org.springframework.samples.petclinic.protobuf.ProtoPetOwner owner = 5;</code>
   * @return Whether the owner field is set.
   */
  @java.lang.Override
  public boolean hasOwner() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.org.springframework.samples.petclinic.protobuf.ProtoPetOwner owner = 5;</code>
   * @return The owner.
   */
  @java.lang.Override
  public org.springframework.samples.petclinic.protobuf.ProtoPetOwner getOwner() {
    return owner_ == null ? org.springframework.samples.petclinic.protobuf.ProtoPetOwner.getDefaultInstance() : owner_;
  }
  /**
   * <code>.org.springframework.samples.petclinic.protobuf.ProtoPetOwner owner = 5;</code>
   */
  @java.lang.Override
  public org.springframework.samples.petclinic.protobuf.ProtoPetOwnerOrBuilder getOwnerOrBuilder() {
    return owner_ == null ? org.springframework.samples.petclinic.protobuf.ProtoPetOwner.getDefaultInstance() : owner_;
  }

  public static final int VISITS_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private java.util.List<org.springframework.samples.petclinic.protobuf.ProtoPetVisit> visits_;
  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPetVisit visits = 6;</code>
   */
  @java.lang.Override
  public java.util.List<org.springframework.samples.petclinic.protobuf.ProtoPetVisit> getVisitsList() {
    return visits_;
  }
  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPetVisit visits = 6;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.springframework.samples.petclinic.protobuf.ProtoPetVisitOrBuilder> 
      getVisitsOrBuilderList() {
    return visits_;
  }
  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPetVisit visits = 6;</code>
   */
  @java.lang.Override
  public int getVisitsCount() {
    return visits_.size();
  }
  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPetVisit visits = 6;</code>
   */
  @java.lang.Override
  public org.springframework.samples.petclinic.protobuf.ProtoPetVisit getVisits(int index) {
    return visits_.get(index);
  }
  /**
   * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPetVisit visits = 6;</code>
   */
  @java.lang.Override
  public org.springframework.samples.petclinic.protobuf.ProtoPetVisitOrBuilder getVisitsOrBuilder(
      int index) {
    return visits_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(birthDate_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, birthDate_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(petType_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, petType_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(5, getOwner());
    }
    for (int i = 0; i < visits_.size(); i++) {
      output.writeMessage(6, visits_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(birthDate_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, birthDate_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(petType_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, petType_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getOwner());
    }
    for (int i = 0; i < visits_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, visits_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.springframework.samples.petclinic.protobuf.ProtoPet)) {
      return super.equals(obj);
    }
    org.springframework.samples.petclinic.protobuf.ProtoPet other = (org.springframework.samples.petclinic.protobuf.ProtoPet) obj;

    if (getId()
        != other.getId()) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (!getBirthDate()
        .equals(other.getBirthDate())) return false;
    if (!getPetType()
        .equals(other.getPetType())) return false;
    if (hasOwner() != other.hasOwner()) return false;
    if (hasOwner()) {
      if (!getOwner()
          .equals(other.getOwner())) return false;
    }
    if (!getVisitsList()
        .equals(other.getVisitsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + BIRTH_DATE_FIELD_NUMBER;
    hash = (53 * hash) + getBirthDate().hashCode();
    hash = (37 * hash) + PET_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getPetType().hashCode();
    if (hasOwner()) {
      hash = (37 * hash) + OWNER_FIELD_NUMBER;
      hash = (53 * hash) + getOwner().hashCode();
    }
    if (getVisitsCount() > 0) {
      hash = (37 * hash) + VISITS_FIELD_NUMBER;
      hash = (53 * hash) + getVisitsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.springframework.samples.petclinic.protobuf.ProtoPet parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.springframework.samples.petclinic.protobuf.ProtoPet parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.springframework.samples.petclinic.protobuf.ProtoPet parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.springframework.samples.petclinic.protobuf.ProtoPet parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.springframework.samples.petclinic.protobuf.ProtoPet parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.springframework.samples.petclinic.protobuf.ProtoPet parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.springframework.samples.petclinic.protobuf.ProtoPet parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.springframework.samples.petclinic.protobuf.ProtoPet parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.springframework.samples.petclinic.protobuf.ProtoPet parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.springframework.samples.petclinic.protobuf.ProtoPet parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.springframework.samples.petclinic.protobuf.ProtoPet parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.springframework.samples.petclinic.protobuf.ProtoPet parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.springframework.samples.petclinic.protobuf.ProtoPet prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.springframework.samples.petclinic.protobuf.ProtoPet}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.springframework.samples.petclinic.protobuf.ProtoPet)
      org.springframework.samples.petclinic.protobuf.ProtoPetOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.springframework.samples.petclinic.protobuf.Petclinic.internal_static_org_springframework_samples_petclinic_protobuf_ProtoPet_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.springframework.samples.petclinic.protobuf.Petclinic.internal_static_org_springframework_samples_petclinic_protobuf_ProtoPet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.springframework.samples.petclinic.protobuf.ProtoPet.class, org.springframework.samples.petclinic.protobuf.ProtoPet.Builder.class);
    }

    // Construct using org.springframework.samples.petclinic.protobuf.ProtoPet.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getOwnerFieldBuilder();
        getVisitsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = 0;
      name_ = "";
      birthDate_ = "";
      petType_ = "";
      owner_ = null;
      if (ownerBuilder_ != null) {
        ownerBuilder_.dispose();
        ownerBuilder_ = null;
      }
      if (visitsBuilder_ == null) {
        visits_ = java.util.Collections.emptyList();
      } else {
        visits_ = null;
        visitsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000020);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.springframework.samples.petclinic.protobuf.Petclinic.internal_static_org_springframework_samples_petclinic_protobuf_ProtoPet_descriptor;
    }

    @java.lang.Override
    public org.springframework.samples.petclinic.protobuf.ProtoPet getDefaultInstanceForType() {
      return org.springframework.samples.petclinic.protobuf.ProtoPet.getDefaultInstance();
    }

    @java.lang.Override
    public org.springframework.samples.petclinic.protobuf.ProtoPet build() {
      org.springframework.samples.petclinic.protobuf.ProtoPet result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.springframework.samples.petclinic.protobuf.ProtoPet buildPartial() {
      org.springframework.samples.petclinic.protobuf.ProtoPet result = new org.springframework.samples.petclinic.protobuf.ProtoPet(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(org.springframework.samples.petclinic.protobuf.ProtoPet result) {
      if (visitsBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0)) {
          visits_ = java.util.Collections.unmodifiableList(visits_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.visits_ = visits_;
      } else {
        result.visits_ = visitsBuilder_.build();
      }
    }

    private void buildPartial0(org.springframework.samples.petclinic.protobuf.ProtoPet result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.birthDate_ = birthDate_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.petType_ = petType_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.owner_ = ownerBuilder_ == null
            ? owner_
            : ownerBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.springframework.samples.petclinic.protobuf.ProtoPet) {
        return mergeFrom((org.springframework.samples.petclinic.protobuf.ProtoPet)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.springframework.samples.petclinic.protobuf.ProtoPet other) {
      if (other == org.springframework.samples.petclinic.protobuf.ProtoPet.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getBirthDate().isEmpty()) {
        birthDate_ = other.birthDate_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getPetType().isEmpty()) {
        petType_ = other.petType_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.hasOwner()) {
        mergeOwner(other.getOwner());
      }
      if (visitsBuilder_ == null) {
        if (!other.visits_.isEmpty()) {
          if (visits_.isEmpty()) {
            visits_ = other.visits_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureVisitsIsMutable();
            visits_.addAll(other.visits_);
          }
          onChanged();
        }
      } else {
        if (!other.visits_.isEmpty()) {
          if (visitsBuilder_.isEmpty()) {
            visitsBuilder_.dispose();
            visitsBuilder_ = null;
            visits_ = other.visits_;
            bitField0_ = (bitField0_ & ~0x00000020);
            visitsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getVisitsFieldBuilder() : null;
          } else {
            visitsBuilder_.addAllMessages(other.visits_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              id_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              birthDate_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              petType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getOwnerFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              org.springframework.samples.petclinic.protobuf.ProtoPetVisit m =
                  input.readMessage(
                      org.springframework.samples.petclinic.protobuf.ProtoPetVisit.parser(),
                      extensionRegistry);
              if (visitsBuilder_ == null) {
                ensureVisitsIsMutable();
                visits_.add(m);
              } else {
                visitsBuilder_.addMessage(m);
              }
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int id_ ;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {

      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object birthDate_ = "";
    /**
     * <code>string birth_date = 3;</code>
     * @return The birthDate.
     */
    public java.lang.String getBirthDate() {
      java.lang.Object ref = birthDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        birthDate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string birth_date = 3;</code>
     * @return The bytes for birthDate.
     */
    public com.google.protobuf.ByteString
        getBirthDateBytes() {
      java.lang.Object ref = birthDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        birthDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string birth_date = 3;</code>
     * @param value The birthDate to set.
     * @return This builder for chaining.
     */
    public Builder setBirthDate(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      birthDate_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string birth_date = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearBirthDate() {
      birthDate_ = getDefaultInstance().getBirthDate();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string birth_date = 3;</code>
     * @param value The bytes for birthDate to set.
     * @return This builder for chaining.
     */
    public Builder setBirthDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      birthDate_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object petType_ = "";
    /**
     * <code>string pet_type = 4;</code>
     * @return The petType.
     */
    public java.lang.String getPetType() {
      java.lang.Object ref = petType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        petType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string pet_type = 4;</code>
     * @return The bytes for petType.
     */
    public com.google.protobuf.ByteString
        getPetTypeBytes() {
      java.lang.Object ref = petType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        petType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string pet_type = 4;</code>
     * @param value The petType to set.
     * @return This builder for chaining.
     */
    public Builder setPetType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      petType_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string pet_type = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPetType() {
      petType_ = getDefaultInstance().getPetType();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string pet_type = 4;</code>
     * @param value The bytes for petType to set.
     * @return This builder for chaining.
     */
    public Builder setPetTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      petType_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private org.springframework.samples.petclinic.protobuf.ProtoPetOwner owner_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.springframework.samples.petclinic.protobuf.ProtoPetOwner, org.springframework.samples.petclinic.protobuf.ProtoPetOwner.Builder, org.springframework.samples.petclinic.protobuf.ProtoPetOwnerOrBuilder> ownerBuilder_;
    /**
     * <code>.org.springframework.samples.petclinic.protobuf.ProtoPetOwner owner = 5;</code>
     * @return Whether the owner field is set.
     */
    public boolean hasOwner() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>.org.springframework.samples.petclinic.protobuf.ProtoPetOwner owner = 5;</code>
     * @return The owner.
     */
    public org.springframework.samples.petclinic.protobuf.ProtoPetOwner getOwner() {
      if (ownerBuilder_ == null) {
        return owner_ == null ? org.springframework.samples.petclinic.protobuf.ProtoPetOwner.getDefaultInstance() : owner_;
      } else {
        return ownerBuilder_.getMessage();
      }
    }
    /**
     * <code>.org.springframework.samples.petclinic.protobuf.ProtoPetOwner owner = 5;</code>
     */
    public Builder setOwner(org.springframework.samples.petclinic.protobuf.ProtoPetOwner value) {
      if (ownerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        owner_ = value;
      } else {
        ownerBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.org.springframework.samples.petclinic.protobuf.ProtoPetOwner owner = 5;</code>
     */
    public Builder setOwner(
        org.springframework.samples.petclinic.protobuf.ProtoPetOwner.Builder builderForValue) {
      if (ownerBuilder_ == null) {
        owner_ = builderForValue.build();
      } else {
        ownerBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.org.springframework.samples.petclinic.protobuf.ProtoPetOwner owner = 5;</code>
     */
    public Builder mergeOwner(org.springframework.samples.petclinic.protobuf.ProtoPetOwner value) {
      if (ownerBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          owner_ != null &&
          owner_ != org.springframework.samples.petclinic.protobuf.ProtoPetOwner.getDefaultInstance()) {
          getOwnerBuilder().mergeFrom(value);
        } else {
          owner_ = value;
        }
      } else {
        ownerBuilder_.mergeFrom(value);
      }
      if (owner_ != null) {
        bitField0_ |= 0x00000010;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.org.springframework.samples.petclinic.protobuf.ProtoPetOwner owner = 5;</code>
     */
    public Builder clearOwner() {
      bitField0_ = (bitField0_ & ~0x00000010);
      owner_ = null;
      if (ownerBuilder_ != null) {
        ownerBuilder_.dispose();
        ownerBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.org.springframework.samples.petclinic.protobuf.ProtoPetOwner owner = 5;</code>
     */
    public org.springframework.samples.petclinic.protobuf.ProtoPetOwner.Builder getOwnerBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getOwnerFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.springframework.samples.petclinic.protobuf.ProtoPetOwner owner = 5;</code>
     */
    public org.springframework.samples.petclinic.protobuf.ProtoPetOwnerOrBuilder getOwnerOrBuilder() {
      if (ownerBuilder_ != null) {
        return ownerBuilder_.getMessageOrBuilder();
      } else {
        return owner_ == null ?
            org.springframework.samples.petclinic.protobuf.ProtoPetOwner.getDefaultInstance() : owner_;
      }
    }
    /**
     * <code>.org.springframework.samples.petclinic.protobuf.ProtoPetOwner owner = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.springframework.samples.petclinic.protobuf.ProtoPetOwner, org.springframework.samples.petclinic.protobuf.ProtoPetOwner.Builder, org.springframework.samples.petclinic.protobuf.ProtoPetOwnerOrBuilder> 
        getOwnerFieldBuilder() {
      if (ownerBuilder_ == null) {
        ownerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.springframework.samples.petclinic.protobuf.ProtoPetOwner, org.springframework.samples.petclinic.protobuf.ProtoPetOwner.Builder, org.springframework.samples.petclinic.protobuf.ProtoPetOwnerOrBuilder>(
                getOwner(),
                getParentForChildren(),
                isClean());
        owner_ = null;
      }
      return ownerBuilder_;
    }

    private java.util.List<org.springframework.samples.petclinic.protobuf.ProtoPetVisit> visits_ =
      java.util.Collections.emptyList();
    private void ensureVisitsIsMutable() {
      if (!((bitField0_ & 0x00000020) != 0)) {
        visits_ = new java.util.ArrayList<org.springframework.samples.petclinic.protobuf.ProtoPetVisit>(visits_);
        bitField0_ |= 0x00000020;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.springframework.samples.petclinic.protobuf.ProtoPetVisit, org.springframework.samples.petclinic.protobuf.ProtoPetVisit.Builder, org.springframework.samples.petclinic.protobuf.ProtoPetVisitOrBuilder> visitsBuilder_;

    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPetVisit visits = 6;</code>
     */
    public java.util.List<org.springframework.samples.petclinic.protobuf.ProtoPetVisit> getVisitsList() {
      if (visitsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(visits_);
      } else {
        return visitsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPetVisit visits = 6;</code>
     */
    public int getVisitsCount() {
      if (visitsBuilder_ == null) {
        return visits_.size();
      } else {
        return visitsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPetVisit visits = 6;</code>
     */
    public org.springframework.samples.petclinic.protobuf.ProtoPetVisit getVisits(int index) {
      if (visitsBuilder_ == null) {
        return visits_.get(index);
      } else {
        return visitsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPetVisit visits = 6;</code>
     */
    public Builder setVisits(
        int index, org.springframework.samples.petclinic.protobuf.ProtoPetVisit value) {
      if (visitsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVisitsIsMutable();
        visits_.set(index, value);
        onChanged();
      } else {
        visitsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPetVisit visits = 6;</code>
     */
    public Builder setVisits(
        int index, org.springframework.samples.petclinic.protobuf.ProtoPetVisit.Builder builderForValue) {
      if (visitsBuilder_ == null) {
        ensureVisitsIsMutable();
        visits_.set(index, builderForValue.build());
        onChanged();
      } else {
        visitsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPetVisit visits = 6;</code>
     */
    public Builder addVisits(org.springframework.samples.petclinic.protobuf.ProtoPetVisit value) {
      if (visitsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVisitsIsMutable();
        visits_.add(value);
        onChanged();
      } else {
        visitsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPetVisit visits = 6;</code>
     */
    public Builder addVisits(
        int index, org.springframework.samples.petclinic.protobuf.ProtoPetVisit value) {
      if (visitsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVisitsIsMutable();
        visits_.add(index, value);
        onChanged();
      } else {
        visitsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPetVisit visits = 6;</code>
     */
    public Builder addVisits(
        org.springframework.samples.petclinic.protobuf.ProtoPetVisit.Builder builderForValue) {
      if (visitsBuilder_ == null) {
        ensureVisitsIsMutable();
        visits_.add(builderForValue.build());
        onChanged();
      } else {
        visitsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPetVisit visits = 6;</code>
     */
    public Builder addVisits(
        int index, org.springframework.samples.petclinic.protobuf.ProtoPetVisit.Builder builderForValue) {
      if (visitsBuilder_ == null) {
        ensureVisitsIsMutable();
        visits_.add(index, builderForValue.build());
        onChanged();
      } else {
        visitsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPetVisit visits = 6;</code>
     */
    public Builder addAllVisits(
        java.lang.Iterable<? extends org.springframework.samples.petclinic.protobuf.ProtoPetVisit> values) {
      if (visitsBuilder_ == null) {
        ensureVisitsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, visits_);
        onChanged();
      } else {
        visitsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPetVisit visits = 6;</code>
     */
    public Builder clearVisits() {
      if (visitsBuilder_ == null) {
        visits_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
      } else {
        visitsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPetVisit visits = 6;</code>
     */
    public Builder removeVisits(int index) {
      if (visitsBuilder_ == null) {
        ensureVisitsIsMutable();
        visits_.remove(index);
        onChanged();
      } else {
        visitsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPetVisit visits = 6;</code>
     */
    public org.springframework.samples.petclinic.protobuf.ProtoPetVisit.Builder getVisitsBuilder(
        int index) {
      return getVisitsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPetVisit visits = 6;</code>
     */
    public org.springframework.samples.petclinic.protobuf.ProtoPetVisitOrBuilder getVisitsOrBuilder(
        int index) {
      if (visitsBuilder_ == null) {
        return visits_.get(index);  } else {
        return visitsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPetVisit visits = 6;</code>
     */
    public java.util.List<? extends org.springframework.samples.petclinic.protobuf.ProtoPetVisitOrBuilder> 
         getVisitsOrBuilderList() {
      if (visitsBuilder_ != null) {
        return visitsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(visits_);
      }
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPetVisit visits = 6;</code>
     */
    public org.springframework.samples.petclinic.protobuf.ProtoPetVisit.Builder addVisitsBuilder() {
      return getVisitsFieldBuilder().addBuilder(
          org.springframework.samples.petclinic.protobuf.ProtoPetVisit.getDefaultInstance());
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPetVisit visits = 6;</code>
     */
    public org.springframework.samples.petclinic.protobuf.ProtoPetVisit.Builder addVisitsBuilder(
        int index) {
      return getVisitsFieldBuilder().addBuilder(
          index, org.springframework.samples.petclinic.protobuf.ProtoPetVisit.getDefaultInstance());
    }
    /**
     * <code>repeated .org.springframework.samples.petclinic.protobuf.ProtoPetVisit visits = 6;</code>
     */
    public java.util.List<org.springframework.samples.petclinic.protobuf.ProtoPetVisit.Builder> 
         getVisitsBuilderList() {
      return getVisitsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.springframework.samples.petclinic.protobuf.ProtoPetVisit, org.springframework.samples.petclinic.protobuf.ProtoPetVisit.Builder, org.springframework.samples.petclinic.protobuf.ProtoPetVisitOrBuilder> 
        getVisitsFieldBuilder() {
      if (visitsBuilder_ == null) {
        visitsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.springframework.samples.petclinic.protobuf.ProtoPetVisit, org.springframework.samples.petclinic.protobuf.ProtoPetVisit.Builder, org.springframework.samples.petclinic.protobuf.ProtoPetVisitOrBuilder>(
                visits_,
                ((bitField0_ & 0x00000020) != 0),
                getParentForChildren(),
                isClean());
        visits_ = null;
      }
      return visitsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.springframework.samples.petclinic.protobuf.ProtoPet)
  }

  // @@protoc_insertion_point(class_scope:org.springframework.samples.petclinic.protobuf.ProtoPet)
  private static final org.springframework.samples.petclinic.protobuf.ProtoPet DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.springframework.samples.petclinic.protobuf.ProtoPet();
  }

  public static org.springframework.samples.petclinic.protobuf.ProtoPet getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProtoPet>
      PARSER = new com.google.protobuf.AbstractParser<ProtoPet>() {
    @java.lang.Override
    public ProtoPet parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ProtoPet> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProtoPet> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.springframework.samples.petclinic.protobuf.ProtoPet getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

